### ISSUE TITLE
Parse time increases significantly for higher fixed repeat values

### ISSUE THREAD

**Issue by evfredericksen** [lark-parser/lark#108]
Hi,

I'm noticing an issue regarding parse time for higher fixed repeat values. The grammar I'm using is dynamically generated and used for matching spoken commands. One example:

rule_code: w3
rule_media: w6
rule_bash: w9
rule_terminal: w12
rule_optional_number: g15
rule_cmdprompt: w21
rule_windows: g24
r28: (("start" "excel"))
r32: (("start" "terminal"))
w3: "code"
w6: "media"
w9: "bash"
w12: "terminal"
g15: ("0" | "1" | "2")~0..1
w21: "command" "prompt"
g24: rule_code | rule_bash | rule_media
rule__dictate: WORD+
%import common.WORD
%ignore " "
start: (rule_code | rule_media | rule_bash | rule_terminal | rule_optional_number | rule_cmdprompt | rule_windows)~1..99

Trying to parse this times out, while switching the start "~1..99" to "+" allows it to parse almost instantly. However, it would be nice to be able to match larger repetitions starting at numbers other than 0 or 1 (like {m,} in regex), as well as fixed higher repetitions (~10 also timed out). Is there any way some of these cases could be optimized?

Thanks for the amazing library!

Edit: Just to clarify, this is referring to initializing an instance of the Lark class.

**Comment by erezsh** [comment]
Hi, thanks for reporting this issue. Lark currently expands choice and fixed repetition as macros. When you combine the two, it explodes combinatorically.

As a quick fix, you can try to rewrite start as:

    start_item: (rule_code | rule_media | rule_bash | rule_terminal | rule_optional_number | rule_cmdprompt | rule_windows)
    start: start_item~1..99

It still loads slower than desirable, but much faster than the original.

Maybe the correct solution is to implement this feature with post-parsing validation, instead of  grammar manipulations. I'll give it some thought!

**Comment by evfredericksen** [comment]
Adding another level helped considerably. Thanks for the response.

**Comment by erezsh** [comment]
Closing. This bug is now represented by issue #190
