### ISSUE TITLE
How to match a terminal which is "arbitrary but fixed"?

### ISSUE THREAD

**Issue by hf-kklein** [lark-parser/lark#1090]
**What is your question?**

In a rule, I want to match a certain combination of terminals which are arbitrary but fixed.
(Sorry, I don't know the correct vocabulary.)

**If you're having trouble with your code or grammar**
Here's my grammar (minimal working example):

```
start:my_rule
my_rule: THREE_CHARACTERS FIVE_DIGITS THREE_CHARACTERS
FIVE_DIGITS: /\d{5}/
THREE_CHARACTERS: /[A-Z]{3}/
%ignore WS
%import common.WS
```

In `my_rule` I want `THREE_CHARACTERS` to be arbitrary but constant. See the table below:

| input | expected result | actual result |
|-------|-----------------|---------------|
| `FOO 12345 FOO` | ✔️ | ✔️ |
| `BAR 12345 BAR` | ✔️ | ✔️ |
| `BAR 12345 FOO` | ❌ | ✔️ |
| `FOO 12345 BAR` | ❌ | ✔️ |

As you see my grammar is not strict enough. It also matches those lines where the first occurence of `THREE_CHARACTERS` is different form the second occurence of `THREE_CHARACTERS`. I understand that this is just how it works for my grammar but is there a way to have a arbitrary but fixed terminal?

**Comment by erezsh** [comment]
In the world of grammars, what you're referring to is called a "context-sensitive" grammar.  That is in contrast to a "context-free" grammar, which is the category that Lark's algorithms are built to parse.

In plain words, you can't have a symbol depend on the value of another symbol.

There are four possible approaches to this issue:

1) Enumerate all the possible values. i.e.  `a x a | b x b | c x c` etc. This probably doesn't apply to your situation

2) Use regexps, which aren't in themselves context-free. i.e. you can use back-references like `/([A-Z]{3})(\d{5})(\1)/`. This is still limiting, since regexps aren't as powerful as a parser.

3) Parse normally, and validate afterwards. The parser won't be able to make parsing decisions based on whether the terminals have the same value or not, but if it doesn't have to, this would be the easiest solution.

4) Use Lark's `parse_interactive()` to advance the parse state-by-state, and ensure that the value of those tokens is the same, and backtrack (by saving copies of the relevant InteractiveParser instance) or raise an error otherwise. It's a little complicated, but it should work.

**Comment by hf-kklein** [comment]
Thanks for your long explanation!
