### ISSUE TITLE
Does regex overrule the default lark grammar?

### ISSUE THREAD

**Issue by awa5114** [lark-parser/lark#1124]
**What is your question?**

I cannot get a simple parser containing a regex string to compile. What am I doing wrong in the grammar?

**If you're having trouble with your code or grammar**

Here's my grammar:

```
value: item ";" item ";" item

item: SIGNED_NUMBER | STRING

STRING: /.+/

%import common.SIGNED_NUMBER
%import common.WS
%ignore WS
```

Here's the text file I want to parse:

```
hello(w,orld);2;3
```

Here's my python code:

```
from lark import Lark

with open('grammar.lark') as fs:
  parser = Lark(fs.read(), start='value')

with open('text.txt') as fs:
  tree = parser.parse(fs.read())

print(tree.pretty())
```

When I run the script I get the following error:

>lark.exceptions.UnexpectedEOF: Unexpected end-of-input. Expected one of: * SEMICOLON

Does the lark grammar overrule the regex? If not how can I match the unquoted string `hello(w,orld)`?

**Comment by MegaIng** [comment]
regex does overrule the grammar, i.e. the terminal is matched as long as possible, which in this case is the full string.

In general, the kind of thing you are describing is really ambiguous and almost impossible to parse. E.g., what should lark do for `1;2;3;4`? Should it be `['1;2', '3', '4']`? Should it fail?. If it is the latter, that is somewhat simple to do, since you can just make `STRING` not match the `;` with something like `STRING: /[^;]+/`. If it's the first, you can try to do something with `parser='earley', lexer='dynamic_complete'`: https://github.com/lark-parser/lark/blob/master/examples/advanced/dynamic_complete.py

**Comment by awa5114** [comment]
It should fail for `1;2;3;4`. I tried your suggestion with `STRING: /[^;]+/` and it seems to work. However I'm a bit confused because the [regex you propose](https://regexr.com/6h1se) will match *everything* which is not a semicolon `;`. Why does lark-parser then only take the first occurrence? Namely `hello(w,orld)`?

**Comment by awa5114** [comment]
Is there an option to activate the global flag? Or would that somehow go against how `lark-parser` is meant to be used?

**Comment by MegaIng** [comment]
It doesn't really make sense. What would it do?

**Comment by erezsh** [comment]
@awa5114 It might be more constructive if you give an example of the language you're trying to parse, and what you expect as the result. What are you trying to achieve?
