### ISSUE TITLE
Syntax highlighting for grammar files?

### ISSUE THREAD

**Issue by RyannDaGreat** [lark-parser/lark#132]
Hi, sorry if this is a dumb question, but is there any way I could get syntax highlighting and/or linting for writing the grammar files (in sublime, or some other editor)? I often find code much easier to debug and learn with this.

**Comment by erezsh** [comment]
Great question, this is still work in progress. We're talking about it in issue #116.

**Comment by RobRoseKnows** [comment]
@RyannDaGreat since more has been done since you originally posted this issue, you can currently get the highlighting in Sublime by Adding [this Repository](https://github.com/lark-parser/lark_syntax) to Package Control and then installing the `lark_syntax` package. I don't think it has been added to the Package Control global repo yet, so for now you'll just have to do it this way. You'll also need to change your file extension to `.lark`, which is the new file extension.

**Comment by brupelo** [comment]
@RobRoseKnows Thanks, that package is quite nice, little note though, if you also want to syntax highlight .g files (used currently on the lark examples), just modify lark.tmLanguage and add:

    <key>fileTypes</key>
    <array>
        <string>g</string>
        <string>lark</string>
        <string>lr</string>
    </array>

**Comment by erezsh** [comment]
@brupelo  That's temporary. The extensions in the example will soon change to `.lark`.

**Comment by erezsh** [comment]
Closing this issue. Syntax highlighters can be found here: https://github.com/lark-parser
