### ISSUE TITLE
Parser throws error if text to parse doesn't end with a new line.

### ISSUE THREAD

**Issue by RobRoseKnows** [lark-parser/lark#139]
This was a problem I came across in a grammar I was writing, but I was able to reproduce it with some of the examples. I don't know if this is Lark working as designed and just grammars are defined incorrectly, or if this is a problem with Lark.

If you start a grammar with a line like: `start: (_item | _NL)*` and then try to read a file that doesn't end with a new line, it will throw a bad parse error. Reproduce by using [lark.lark](https://github.com/lark-parser/lark/blob/master/examples/lark.g) as the grammar and then try to parse it without a `\n` at the end of the file.

The easy solution to this is, of course, just add a newline at the end of any string you want to parse. But this doesn't feel like a very good solution. Any thoughts of how to fix?

**Comment by erezsh** [comment]
The reason that `lark.lark` requires files to end in a newline is because of the way its rules are written: You can see that `rule`, `token` and `statement` all require _NL at the end. The reason I wrote it like this is that making _NL optional would make it harder to parse with LALR(1).

But now that you mention it, I have a different idea. I can add an EOF symbol, something like:

    rule: RULE priority? ":" expansions (_NL|$)

**Comment by RobRoseKnows** [comment]
Yeah, I think adding an EOF symbol would be a good idea. Especially since Windows is now using Unix line endings in Notepad by default.

**Comment by Vesuvium** [comment]
I can see the usefulness of an EOF token too, so you should definitely consider adding it

**Comment by erezsh** [comment]
Closing. This idea of adding EOF continues in issue #237
