### ISSUE TITLE
JSON benchmarks revisited

### ISSUE THREAD

**Issue by goodmami** [lark-parser/lark#218]
Hi, I'm excited by Lark's speed claims but I'm having trouble replicating. This GitHub issue is more informational than an actual bug report, but I'd be happy to hear your thoughts.

I wrote a JSON parser (below) with Parsimonious that was faster than [the one you benchmarked with](https://gist.github.com/reclosedev/5222560) (by @reclosedev); mine also parses floats better and empty objects (`{}`) and arrays (`[]`), based on some pattern optimizations I'd found previously (https://github.com/erikrose/parsimonious/issues/119). My NodeVisitor is based on the one by @reclosedev. When I run the parser and Lark's (with and without a NodeVisitor/Transformer) over a small JSON example 10000 times, I get these times:

| implementation | time (tree only) | time (transformed) |
| --- | --- | --- |
| parsimonious (original) | 4.33s | 8.08s |
| parsimonious (mine) | 2.31s | 4.31s |
| lark | 3.41s | 3.52s |

The comparison with transformation is somewhat in-line to the claimed speeds, but the difference is much less with my optimized Parsimonious parser, and mine even beats Lark when there is no tree transformation (this has limited utility, but it also shows how slow Parsimonious's NodeVisitor is compared to Lark's tree-less parsing, perhaps because Parsimonious builds the Tree *and* the transformation, so maybe the numbers aren't directly comparable).

For further comparison, I wrote a Cython-based recursive descent parser with highly tuned pattern recognition but no grammar optimizations, and get these times compared to Python's C-based `json` module. Note that it does not create a tree, but it can 'scan' without transforming.

| implementation | time (scan only) | time (transformed) |
| --- | --- | --- |
| cython | 0.057s | 0.177s |
| json | n/a | 0.052s |

This perhaps lends support to #114. I found that creating Python objects (even just tuples) slows down things a lot. With Cython I could avoid the dynamic type-checking and use simple structs, which look like tuples in Python, and they are much faster to create.

It could be that my use case of parsing a small JSON object many times instead of one giant one has a different performance profile. Also, it's worth noting that recursive descent would use a ton of memory to parse large objects, so speed isn't everything.

Here is my Parsimonious-based parser:

```python
    Json = Grammar(r'''
        Start    = Object / Array
        Object   = ~"{\s*" Members? ~"\s*}"
        Members  = MappingComma* Mapping
        MappingComma = Mapping ~"\s*,\s*"
        Mapping  = DQString ~"\s*:\s*" Value
        Array    = ~"\[\s*" Items? ~"\s*\]"
        Items    = ValueComma* Value
        ValueComma = Value ~"\s*,\s*" 
        Value    = Object / Array / DQString
                 / TrueVal / FalseVal / NullVal / Float / Integer
        TrueVal  = "true"
        FalseVal = "false"
        NullVal  = "null"
        DQString = ~"\"[^\"\\\\]*(?:\\\\.[^\"\\\\]*)*\""
        Float    = ~"[-+]?(\d+(\.\d*)?|\.\d+)([eE][-+]?\d+)?"
        Integer  = ~"[-+]?\d+"
    ''')

    class JsonVisitor(NodeVisitor):
        """ Produces Python objects from parsed JSON grammar tree
        """
        def generic_visit(self, node, visited_children):
            return visited_children or node

        # helper functions for generic patterns
        def combine_many_or_one(self, node, children):
            """ Usable for following pattern:
    
                values = value_and_comma* value
            """
            members, member = children
            if isinstance(members, list):
                return members + [member]
            return [member]

        def lift_first_child(self, node, visited_children):
            """ Returns first child from `visited_children`, e.g. for::
    
                rule = item optional another_optional?
    
            returns `item`
            """
            return visited_children[0]

        # visitors
        visit_Start = visit_Value = visit_MappingComma = visit_ValueComma = lift_first_child
        visit_Members = combine_many_or_one

        def visit_Object(self, node, children):
            _, members, _ = children
            if isinstance(members, list):
                members = members[0]
            else:
                members = []
            return dict(members)

        def visit_Array(self, node, children):
            _, values, _ = children
            if isinstance(values, list):
                values = values[0]
            else:
                values = []
            return values

        def visit_Mapping(self, node, children):
            key, _, value = children
            return key, value

        def visit_DQString(self, node, visited_children):
            # produce unicode for strings
            return ast.literal_eval("u" + node.text)

        def visit_Float(self, node, visited_children):
            return float(node.text)

        def visit_Integer(self, node, visited_children):
            return int(node.text)

        def visit_TrueVal(self, node, visited_children):
            return True

        def visit_FalseVal(self, node, visited_children):
            return False

        def visit_NullVal(self, node, visited_children):
            return None
```

The Lark-based one is taken from the tutorial with these invocations:

```python
    Json1 = Lark(json_grammar, parser='lalr', lexer='standard')
    Json2 = Lark(json_grammar, parser='lalr', lexer='standard', transformer=TreeToJson())
```

Finally, here is my test case:

```javascript
{
    "bool": [
        true,
        false
    ],
    "number": {
        "float": -0.14e3,
        "int": 1
    },
    "other": {
        "string": "string",
        "unicode": "あ",
        "null": null
    }
}
```

**Comment by erezsh** [comment]
Hi,

First of all, I'm glad you've taken the time to check my benchmarks and to try to come up with better competition to Lark. I'll address your points in the order you presented them:

I'm not sure it makes sense to measure only the tree construction, any more than it makes sense to measure only the lexer. A parser is a complete product, especially Lark & Parsimonious which offer more than just a parsing engine (and if you want just a *fast engine*, there are C++/Haskell/Rust parsers that I can recommend).

It is interesting to learn that Parsimonious could be faster. Perhaps they should adopt a tree-less option like I have in Lark.

Likewise, Lark makes no claims to beat a parser that's handwritten in Cython. Perhaps a more fair comparison would be against Lark running on PyPy, rather than CPython. I do have plans to write a version of Lark in Cython, but that might take a while. I'll welcome your help, since you seem to know Cython well. Perhaps you can share the Cython parser you already wrote, so I can learn from your experience.

> It could be that my use case of parsing a small JSON object many times instead of one giant one has a different performance profile

That is definitely the case. Because LALR(1) has a non-trivial compilation time, and linear performance, it really shines on long inputs.  If you must test it on shorter inputs, consider using the standalone parser, initializes much faster than the library.

Finally, I benchmarked your parser, on the same 6MB json file I did the other benchmarks. It ran for 15 seconds (better than the previous 20 seconds), and quit with the following error:

    IncompleteParseError: Rule 'Start' matched in its entirety, but it didn't consume all the text. The non-matching portion of the text begins with '
' (line 225002, column 2).

If you wish to fix the parser and resubmit it, I'll be happy to try it again. I can also provide you with the "offending" json, if you need it.

One little note though: Even if Lark had lost on performance (though I'd definitely say that's not the case), I think writing constructs such as `~"\s*:\s*"` just to gain a few percents might not be worth it, even if you know what you're doing. And definitely not if you're a newbie to parsing, which is a big chunk of Lark's audience.

Thanks again for your input!

**Comment by eerimoq** [comment]
Hello,

I recently implemented a text parser in Python called [textparser](https://github.com/eerimoq/textparser). It's the fastest parser implemented in Python according to my [JSON benchmark](https://github.com/eerimoq/textparser#benchmark), which compares the speed of 10 parsers, including Lark and Parsimonious. Of course, making a fair parser comparison is hard, if not impossible, as different users have different needs.

@goodmami I replaced the [Parsimonious grammar](https://github.com/eerimoq/textparser/blob/master/examples/benchmarks/json/parsers/parsimonious_json.py#L12-L30) in my JSON benchmark with yours, as it was much faster than the original one. There is a reference to your Gist in the beginning of the file.

Thanks,
Erik

**Comment by erezsh** [comment]
@goodmami

I tried replicating your benchmarks, and I ran into some strange behavior. I'd appreciate it if you take a look. Perhaps I'm missing something obvious?

I add a few lines to the first test:

```python
    if args.testnum in (0, 1):
        start = time.time()
        ParsimoniousJson1.match(s)
        print(time.time() - start)
        print(
            'Parsimonious 1 (faster grammar; tree only)\n    ',
            timeit.timeit(
                'ParsimoniousJson1.match(s)',
                setup='from __main__ import ParsimoniousJson1, s',
                number=1
            )
        )        
```

Supposedly, the two times should be equal. However, here's what I get:

    $ python lark_parsim.py 1
    6.77223992348
    ('Parsimonious 1 (faster grammar; tree only)\n    ', 4.235352993011475)

I'm getting the same ratio with Python2, Python3 and PyPy. What am I missing?!

**Comment by goodmami** [comment]
@eerimoq I'm glad it could be useful for you. You're right that a fair comparison is hard. I was trying to be clear that my numbers are valid for the current implementations, the test case, and the grammars used. It's possible that a more efficient Lark grammar could get better numbers, and my Parsimonious grammar could probably be improved more. Performance ratios may differ for tests other than JSON.

@erezsh It looks like maybe garbage collection (see https://stackoverflow.com/a/17579466/1441112). If `timeit` disables garbage collection, then maybe my reported memory usage numbers are inflated due to this. Also, depending on the system, `time.time()` may not return better granularity than seconds, although on my system it was getting fractional seconds (`time.perf_counter()` didn't change anything).

**Comment by erezsh** [comment]
@goodmami 

You're right, it was the garbage collector, good catch! It almost doubled the run-time at some points (not for Lark though).

Out of curiosity, I tried the same "cheats" you used for parsimonious, and it did improve Lark's performance by about 15%. Here's the grammar I used:

```ruby
    ?start: value

    ?value: object
          | array
          | string
          | SIGNED_NUMBER      -> number
          | "true"             -> true
          | "false"            -> false
          | "null"             -> null

    array  : _BRACK1 [value (_COMMA value)*] _BRACK2
    object : _CURLY1 [pair (_COMMA pair)*] _CURLY2
    pair   : string _COLON value

    _COLON: /\s*:\s*/
    _COMMA: /\s*,\s*/
    _CURLY1: /\s*{\s*/
    _CURLY2: /\s*}\s*/
    _BRACK1: /\s*\[\s*/
    _BRACK2: /\s*\]\s*/

    string : ESCAPED_STRING

    %import common.ESCAPED_STRING
    %import common.SIGNED_NUMBER
    %import common.WS

    %ignore WS           
```
And the results, which are a bit closer now for tree-only:

Parsimonious 1 (faster grammar; tree only)
     3.8514347829986946
parsimonious 1 (faster grammar; transformed data)
     6.658515089999128
parsimonious 2 (original grammar; tree only)
     8.252602351996757
parsimonious 2 (original grammar; transformed data)
     13.493692200994701
lark (lalr; tree only)
     4.516857561997313
lark (lalr; tree-less transformation)
     4.552754584001377
lark (lalr; tree and transformation)
    5.624249114996928
json (Python standard library)
     0.0479155040011392

It is interesting that Parsimonious could perform that well, and it makes me want to optimize Lark even further, for example to use ints for ids instead of strings, and arrays instead of dictionaries.

Btw, with PyPy Lark blows everyone out of the water, even with the regular json parser:

    ('Parsimonious 1 (faster grammar; tree only)\n    ', 2.709336042404175)
    ('parsimonious 1 (faster grammar; transformed data)\n    ', 3.4756290912628174)
    ('parsimonious 2 (original grammar; tree only)\n    ', 4.906686067581177)
    ('parsimonious 2 (original grammar; transformed data)\n    ', 6.893182992935181)
    ('lark (lalr; tree only)\n    ', 1.4323079586029053)
    ('lark (lalr; tree-less transformation)\n    ', 1.1859769821166992)
    ('lark (lalr; tree and transformation)\n   ', 1.5206549167633057)
    ('json (Python standard library)\n    ', 0.04317116737365723)

And with the "cheats" it's even better:

    ('lark (lalr; tree only)\n    ', 1.2808449268341064)
    ('lark (lalr; tree-less transformation)\n    ', 1.0889439582824707)
    ('lark (lalr; tree and transformation)\n   ', 1.6545860767364502)

Also, I'm not entirely sure it's fair to discount the effect of the garbage collector, since it means that in real-life runs Parsimonious would be slower than "advertised".

So, yeah, I agree that fair benchmarks are very difficult :)

@eerimoq 

Hi Erik, textparser looks nice and seems to be very fast, so congrats! If you provide a json-parser that also produces correct json, I'll add you to my benchmarks graph.

**Comment by eerimoq** [comment]
@erezsh Parse tree transformations are not yet part of the textparser package, but I implemented it as a separate step after the parsing. Parse tree transformations will become part of the package once there is a need for it. Today only one package uses textparser, and there is no immediate need for transformations in that package.

Here is the JSON parser: https://github.com/eerimoq/textparser/blob/master/examples/json.py

**Comment by erezsh** [comment]
>  I wonder if it's possible to automatically combine patterns that will be thrown away

Yes, it is. At least in some cases. This is one of the advantages of having terminals defined as anonymous in the grammar itself, instead of being filtered out by the user: The parser can merge them without worrying about the structure.

**Comment by erezsh** [comment]
Published the updated benchmarks
