### ISSUE TITLE
Stack Overflow Question

### ISSUE THREAD

**Issue by marketneutral** [lark-parser/lark#219]
Hello,

Would you be able to advise on this question:

https://stackoverflow.com/questions/52115532/lark-parsing-based-on-tree-location

Thanks, and thanks so much for such an awesome parsing package! Lark is amazing.

Best,
Jonathan

**Comment by erezsh** [comment]
Thanks! Glad you like it.

I assume the question has been answered? Let me know if you still need help.

**Comment by marketneutral** [comment]
Thank you. Lark is a really great package. With virtually zero background in parsing I was able to get something actually working in the span of a day (that’s a testament to your package, docs, and examples). 

Yes, I got enough guidance in that StackOverflow thread to get it working. Though I’d be grateful for any comments at all on https://github.com/marketneutral/alphatools/blob/master/alphatools/expression/expression.lark and https://github.com/marketneutral/alphatools/blob/master/alphatools/expression/expression.py.

It’s a first attempt and rapid prototype...

Best regards,
Jonathan

**Comment by erezsh** [comment]
The code looks great!

I would say that perhaps it would be more idiomatic to use Visitor instead of Transformer, since you're not making any changes (i.e. returning values that need to maintain a hierarchy). But it's not important.

I'm closing the issue. Feel free to ask more questions regardless, either here or in the gitter chat:  https://gitter.im/lark-parser/Lobby
