### ISSUE TITLE
License is ambiguous

### ISSUE THREAD

**Issue by pekkaklarck** [lark-parser/lark#247]
According to the README.md and LICENCE files Lark uses the MIT license. The README also states that it's possible to create a standalone parser which would be nice in our project. A problem is that the [provided standalone example](https://github.com/lark-parser/lark/blob/master/examples/standalone/json_parser.py) states that the parser uses GPLv2 or above. Our project is Apache 2 licensed and GPLv2 is not compatible with it. Could you clarify the situation?

**Comment by erezsh** [comment]
Yes, the license for the standalone parser is different from the rest of Lark, because it is standalone. The idea behind it is to prevent commercial companies from including the generated parser in their product without mentioning Lark.

Is your project open-source? If so, let's come up with a solution that allows you to use the standalone parser. I'll consider any solution, such as updating the license, or giving your project a specific authorization (if that's possible under GPLv2), as long as it maintains my original intention.

**Comment by pekkaklarck** [comment]
OK, thanks for clarification. I understand your concerns, but I think it would still be good to mention in the README that the generated standalone parser is GPL, not MIT.

Our project is open source test automation framework hosted at https://github.com/robotframework/robotframework/. We are planning to reimplement test data parsing and currently looking for options. Lark and SLY look promising, but we need more prototyping before making the decision. Authorization to use the generated parser under Apache 2 or compatible license would be needed if we decide to use Lark.

**Comment by erezsh** [comment]
Nice, I'm a fan of robots.

> I think it would still be good to mention in the README

You're right, I'll do that.

> Authorization to use the generated parser under Apache 2 or compatible license would be needed

No problem, I'll be happy to provide it for as long as you stay open-source.

Don't hesitate to let me know if you have any other question you need answered.

**Comment by pekkaklarck** [comment]
Cool, we'll let you know if we decide to go with Lark and need more official authorization, and also if we are stuck with something and would need help.

Notice that although our tool is named Robot Framework, it doesn't have that much to do with real robots. =)
