### ISSUE TITLE
Generating syntax-highlighting schemes for editors?

### ISSUE THREAD

**Issue by j6k4m8** [lark-parser/lark#261]
I've created a grammar for the most perfect programming language in the universe (which no computer scientists will ever find any complaints with!) using lark, so thank you very much. Glad that's solved now.

But now I want to generate, say, a VSCode syntax-highlighting scheme for my language. VSCode accepts a `.tmLanguage.json` file (for example, [here's the JS one](https://github.com/Microsoft/vscode/blob/master/extensions/javascript/syntaxes/JavaScript.tmLanguage.json) but this doesn't look trivially generatable using a Transformer.

This is also insanely hard to google around for, since "lark" and "syntax highlighting" results are almost entirely about support for the `.lark` file format.

Is this an existing capability? Am I overestimating the complexity of rolling my own?

**Comment by erezsh** [comment]
That's amazing. Please share your programming language with us mortals so that we may get a glimpse of divinity.

I'm afraid auto-generating syntax highlighting is very non-trivial, because it's not obvious how to generate the role of each token. i.e. how do we know what's a comment, what's an enum, etc.

**Comment by j6k4m8** [comment]
Got it — wasn't sure if there was an intermediate step where tokens were "typed" and could be leveraged to generate syntax-highlighting. I'll re-open this Issue if I manage to get something working nicely with the Lark codebase!
