### ISSUE TITLE
item+ rule fails

### ISSUE THREAD

**Issue by finjulhich** [lark-parser/lark#301]
The following sample

`sample = """MTH/                 ----"""`

is correctly parsed by this grammar:

```
grammar = """
    start: header1
    header1: "MTH/" myws dashes
    myws: " "+
    dashes: "----"

    %import common (SIGNED_NUMBER, WS, INT, DIGIT, NEWLINE)
"""
```

but not when 
`dashes: "-"+`

Doesn't + apply to string literals?
Is - special?

**Comment by erezsh** [comment]
Provide a fully functioning example.

How do you initialize the Lark instance? Are you using LALR?

**Comment by finjulhich** [comment]
When moved to standalone, I cannot reproduce. It must be the bigger sample and bigger grammar.
A question:
Are these operator allowed for Terminals as well as for Rules?
- pipe | 
- star *
- +

**Comment by finjulhich** [comment]
Would it make sense to update Syntax for Terminals here?
https://lark-parser.readthedocs.io/en/latest/grammar/#terminals

**Comment by erezsh** [comment]
> Would it make sense to update Syntax for Terminals here

Yes. I'll accept a pull request for that.

> Is it correct to say that terminals are produced by the lexer for the parser to consume?

Yes, exactly. Terminals are a way to clump up a bunch of characters together for easy and efficient consumption (like words). The parser then finds structure in them.

It's possible, using the Earley parser, to only use rules. But then you will get lists of characters instead of strings, and it will be much much slower.
