### ISSUE TITLE
Infinite loop 

### ISSUE THREAD

**Issue by abialy** [lark-parser/lark#310]
Hi, 
I have an issue with infinite loop.

My grammar looks like this (I have more complex grammar but I managed to isolate an issue on smaller one):

start: statement+

statement: expression

expression: NUMBER
          | expression BINARY_OP expression

BINARY_OP: "+"  

%import common.ESCAPED_STRING -> _STRING 
%import common.INT -> NUMBER

%import common.WS -> WS
%import common.WS_INLINE
%import common.NEWLINE -> NEWLINE

%ignore WS
%ignore WS_INLINE

When I try to parse the following:

   1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1+1

The parser hangs in a infinite loop. 

Any ideas if that's an issue in the parser or something about grammar. 

Unfortunately, language I try to parse has such (crazy) programs. 

Regards,
Artur

**Comment by erezsh** [comment]
It is a problem with the parser. It's not stuck in an infinite loop, it's just very slow for this specific use-case, where there is a lot of ambiguity.

You have several choices:

* Use `parser="lalr"`. It works for this grammar, and is much much faster. But, it doesn't support every grammar, like earley does.

* Rewrite the arithmetic in a non-ambiguous way. It's not very hard: You can see the "trick" here: https://github.com/lark-parser/lark/blob/master/examples/calc.py

* Use branch `0.7d`, in which this issue is fixed (and potential future ones too).

* Wait for the official `0.7` release, which should happen soon, but no promises.

**Comment by abialy** [comment]
Thank you. My grammar is not LARL compliant, I will try to rewrite it. 

Good to know that the fix is done in next release too.
