### ISSUE TITLE
State becomes broken after failure

### ISSUE THREAD

**Issue by excitoon** [lark-parser/lark#316]
```python
import lark
import lark.indenter

class PythonIndenter(lark.indenter.Indenter):
    NL_type = '_NEWLINE'
    OPEN_PAREN_types = ['LPAR', 'LSQB', 'LBRACE']
    CLOSE_PAREN_types = ['RPAR', 'RSQB', 'RBRACE']
    INDENT_type = '_INDENT'
    DEDENT_type = '_DEDENT'
    tab_len = 8

# This is workaround.
#    def process(self, stream):
#        lark.indenter.Indenter.__init__(self)
#        yield from lark.indenter.Indenter.process(self, stream)

parser = lark.Lark.open('python3.lark', parser='lalr', start='file_input', postlex=PythonIndenter())

c = """
for i in ssss.sss:
    print(i)
        print(i)
"""

try:
    tree = parser.parse(c)
except:
    pass

c = """
for i in ssss.sss:
    print(i)
"""
tree = parser.parse(c)
print(tree)
```

I guess this code is self-describing. After a failure, parser breaks itself (but there is a workaround).

**Comment by excitoon** [comment]
I wonder why you set the variable in two places, here:
https://github.com/lark-parser/lark/commit/b83bac48bdb4706c9819da0825c3344f328611b1#diff-7ed6b419895fb68610374f844fdf019cR31
and here:
https://github.com/lark-parser/lark/commit/b83bac48bdb4706c9819da0825c3344f328611b1#diff-7ed6b419895fb68610374f844fdf019cR53

Personally, I think state should not be stored in `self` properties at all.

**Comment by erezsh** [comment]
I set it at `__init__` because otherwise pylint gives warnings, and it's considered unidiomatic. Maybe I could set them to `None` at first. I didn't really seem important.

One reason to save the properties in `self`, is to allow for better error reporting. For example, you could report which indentation level was expected, using `indenter.indent_level[-1]`

I'm not sure that it's a common enough use-case, but I don't see much harm in keeping it in.

**Comment by excitoon** [comment]
No, I mean in `process` and `_process` (and third time is in `__init__`).

**Comment by erezsh** [comment]
Oh yeah... My bad. Fixed it now, thanks!
