### ISSUE TITLE
Early parser fails to report ambiguous trees

### ISSUE THREAD

**Issue by thebarbershop** [lark-parser/lark#400]
I am working on Python 3.7.3, Lark 0.7.1

Consider the following very simple example:

```python
grammar = r"""
    start           : item_list
    item_list       : item_list? item
    item            : A | B 
    A               : "a" | "ab"
    B               : "b"
"""
parser = Lark(grammar, parser="earley", ambiguity="explicit", debug=True)

result = parser.parse("ab")
print(result.pretty())
```

With the `explicit` option, I expected something like:

```text
start
  __ambig
    item_list
      item_list
        item	a
      item	b
    item_list
      item ab
```

However, the output is:
```
start
  item_list
    item_list
      item	a
    item	b
```

Is this a bug? Or am I misunderstanding something?

**Comment by erezsh** [comment]
What you're trying to do has to be enabled by the user, because it's potentially slow, and most users don't need it.

You can enable it using `Lark(..., lexer='dynamic_complete')`

Or in your case:

```python
parser = Lark(grammar, ambiguity="explicit", lexer='dynamic_complete')
```

**Comment by thebarbershop** [comment]
It behaves differently when I change the order of rules for `A : "a" | "ab"`to `A : "ab" | "a"`. They mean the same thing semantically, don't they?

Here are the two sample outputs:

```python
from lark import Lark
grammar = r"""
    start           : item_list
    item_list       : item_list? item
    item            : A | B 
    A               : "ab" | "a"
    B               : "b"
"""
parser = Lark(grammar, ambiguity="explicit", lexer="dynamic_complete")
result = parser.parse("ab")
print(result.pretty())
```

output (this is what I expect):

```text
start
  _ambig
    item_list
      item      ab
    item_list
      item_list
        item    a
      item      b
```

and the other rule:

```python
from lark import Lark
grammar = r"""
    start           : item_list
    item_list       : item_list? item
    item            : A | B 
    A               : "a" | "ab"
    B               : "b"
"""
parser = Lark(grammar, ambiguity="explicit", lexer="dynamic_complete")
result = parser.parse("ab")
print(result.pretty())
```

output (failing to catch ambiguity):

```text
start
  item_list
    item_list
      item      a
    item        b
```

Using Python 3.7.3, Lark 0.7.1.

**Comment by erezsh** [comment]
That does look like a bug, from a cursory glance. I'll add the "bug" tag until proven otherwise.

@night199uk Do you have any insight to add?

**Comment by erezsh** [comment]
P.S. It might be related to issue #319

**Comment by night199uk** [comment]
will take a look tomorrow hopefully.

**Comment by night199uk** [comment]
Yeah; this is odd, but I'm not sure if it's a bug . The problem in short (skipping some thing for brevity) is that the lexer is only returning one token for A and one token for B.

So there are two scenarios (depending on whether "ab" or "a" is listed first after A):
Scenario 1 (A: "a" | "b")
A matches "a" (lexer only returns a single token)
B matches "b"

Scenario 2 (A: "ab" | "b")
A matches "ab"
B matches "b"

In scenario #2, you can see an ambiguity with the 'dynamic_complete'; because dynamic_complete is a slightly misnomer. It doesn't actually tell the lexer to match all tokens, it tells the parser to dissect the returned token from the lexer and see if it could find a shorter match. So in this case, the lexer (which isn't a real lexer in Xearley but forget that a second), returns "ab" which is then turned into "a" and "ab" because "a" can also match the same pattern.

The question is whether this is a bug; and whether both variations of the lexer pattern:
A: "ab"
 |  "a" 
Should be added to the to_scan buffer for xearley.

I'll look more but @erezsh  what are your thoughts?

**Comment by night199uk** [comment]
Sorry, I should have said. For xearley I think the best workaround is to ignore the lexer:
```
grammar = r"""
    start           : item_list
    item_list       : item_list? item
    item            : a | b 
    a               : "ab" | "a"
    b               : "b"
"""
```
should produce the same output as:
```
grammar = r"""
    start           : item_list
    item_list       : item_list? item
    item            : a | b 
    a               : "a" | "ab"
    b               : "b"
"""
```

**Comment by night199uk** [comment]
Ahhh. 

Yeah, I think the real point here is that  this:
    A               : "ab" | "a"

essentially becomes a single terminal matcher that does this:
A: /ab|a/
or:
A: /a|ab/
This will only call the lexer once (as there is only 1 terminal - it's a terminal remember). The regex will return only one match, no matter what you do. 

If you want two matches, you need to have two potential terminals (or two separate matches), where:
a: "a" | "ab"
equates to:
a: _ANON_1 | _ANON_2
_ANON_1: /a/
_ANON_2: /ab/

Thus allowing *2* matches to be returned as the lexer is called twice with two different pattern matches for two different terminals (ANON_1 and ANON_2). Hope that makes sense?

**Comment by erezsh** [comment]
Yes, you're right. The regexp engine always returns one over the other, I might have missed it.

So there are two approaches to this:

1) Declare this the correct behavior. Require users to use rules if they want ambiguity resolution

2) Implement terminals as a rule anyway behind the scenes, for Earley. Then you get the desired behavior. So `A: "a" | "ab"` becomes `!a: "a" | "ab"`

Honestly, I'm leaning heavily towards the first approach. The second one takes more work, removes flexibility (what if someone wants to solve some ambiguity manually?), and only to fix something that users can easily fix themselves.

But I'm open to be persuaded otherwise. Until then, I consider this as not a bug.

**Comment by thebarbershop** [comment]
@erezsh If you say this is a design by choice but not a bug, I can accept the way it is, as I understand there is a way to overcome this problem with minimal change of rules. Then it should better be documented somewhere, shouldn't it? It is against the natural expectation of most users, so they should know about it.

**Comment by erezsh** [comment]
It's tied to how regular expressions work, and not Lark's implementation (except that it uses regexps), but I'm certainly open to improving the docs and making it clear.

Would you like to draft a paragraph explaining this to new users? I can then editorialize it and find the right place for it in the docs.

**Comment by thebarbershop** [comment]
I'll give it a try in a couple of days.

**Comment by thebarbershop** [comment]
# Header

What happens when you use the OR operator to define terminals is not defined in the document. By implementation detail, it reduces to a single regex as @night199uk  explained, and I think that should be noted in the [terminals](terminals) section in the docs.

> A : "ab" | "a"
>
> essentially becomes a single terminal matcher that does this:
> A: /ab|a/
> or:
> A: /a|ab/

[terminals]: https://lark-parser.readthedocs.io/en/latest/grammar/#terminals

---

## Terminals with the OR operator

Two or more literals connected with the OR operator (`|`) is interpreted as a single regular expression. In the following example, the terminal `A1` is equivalent to `A2`.

**Example**

```
A1 : "a" | "b"
A2: /a|b/
```

When one of the connected literals is a substring of another, it may lead to an unexpected behavior.

**Example**

```
start           : item_list
item_list       : item_list? item
item            : A | B
A               : "a" | "ab"
B               : "b"
```

For the string `ab`, this rule cannot catch the ambiguity but reports the following:

```
start
  item_list
    item_list
      item      a
    item        b
```

If you want two matches, you need to have two potential terminals:

**Example**

```
a: "a" | "ab"
```

equates to:

```
a: _ANON_1 | _ANON_2
_ANON_1: /a/
_ANON_2: /ab/
```

**Comment by thebarbershop** [comment]
I'm not really sure, but do I have to ping you, @erezsh ? Just in case you missed it.

**Comment by erezsh** [comment]
No no, sorry, I saw it, and it's in my task queue. It's a great start, Thanks!

**Comment by thebarbershop** [comment]
Thanks! Just let me know if there is anything I can help with.

**Comment by erezsh** [comment]
Updated. See here: https://lark-parser.readthedocs.io/en/latest/grammar/#terms
