### ISSUE TITLE
Discard exception is not caught in LALR parser

### ISSUE THREAD

**Issue by eddieschoute** [lark-parser/lark#435]
I'm writing a Transformer for my LALR parser and want to simplify some nodes. Some can even be removed, which is why I raise `Discard` in my Transformer as explained in the docs (https://lark-parser.readthedocs.io/en/latest/classes/#transformers-visitors).

I construct the parser as
```
parser = Lark(GRAMMAR, parser='lalr', maybe_placeholders=True, transformer=MyTransformer())
```

I get the following partial stack trace
```
  File "/Users/eddieschoute/dev/openqasm-parser/.venv/src/lark-parser/lark/lark.py", line 306, in parse
    return self.parser.parse(text, start=start)
  File "/Users/eddieschoute/dev/openqasm-parser/.venv/src/lark-parser/lark/parser_frontends.py", line 89, in parse
    return self._parse(token_stream, start, *[sps] if sps is not NotImplemented else [])
  File "/Users/eddieschoute/dev/openqasm-parser/.venv/src/lark-parser/lark/parser_frontends.py", line 54, in _parse
    return self.parser.parse(input, start, *args)
  File "/Users/eddieschoute/dev/openqasm-parser/.venv/src/lark-parser/lark/parsers/lalr_parser.py", line 36, in parse
    return self.parser.parse(*args)
  File "/Users/eddieschoute/dev/openqasm-parser/.venv/src/lark-parser/lark/parsers/lalr_parser.py", line 95, in parse
    reduce(arg)
  File "/Users/eddieschoute/dev/openqasm-parser/.venv/src/lark-parser/lark/parsers/lalr_parser.py", line 76, in reduce
    value = self.callbacks[rule](s)
  File "/Users/eddieschoute/dev/openqasm-parser/.venv/src/lark-parser/lark/parse_tree_builder.py", line 120, in __call__
    return self.node_builder(filtered)
  File "/Users/eddieschoute/dev/openqasm-parser/openqasm/transformer.py", line 61, in qregdecl
    raise Discard()
lark.visitors.Discard
```

On inspection of the LALR stack it doesn't seem like there is a catch for the Discard exception. Is this an oversight? I would like to do this processing during the parsing for efficiency reason.

**Comment by erezsh** [comment]
Yes, the internal Transformer is actually a different implementation, for performance reasons, and the Discard option wasn't coded into it. 

I create a branch that implements it, for **returning** discard, i.e. (`return Discard`)

I'm still a little concerned about merging it to master, because it might degrade performance, which is noticeable in LALR.

But feel free to use it for now: branch `embedded_discard`

**Comment by eddieschoute** [comment]
Thank you for the quick reply. I'll see if I can use this but performance is also a concern for me. Why would you say that it may degrade performance?

**Comment by erezsh** [comment]
Well, you can see it in the fix commit: https://github.com/lark-parser/lark/commit/7dc813b927a6c1efeaa4ff759cab2c07df0cb30c

The solution requires me to add another layer to the parser callback, which will have to iterate over every Tree node's children. Maybe it won't be too noticeable, but it needs to be tested.

**Comment by eddieschoute** [comment]
I see. If it were implemented as a try-catch it may have less performance impact because it will only occur in few cases. Alternatively, you can consider implementing these filters lazily (without instantiating the children list). Then the filter would be transparent to any consumer (that takes in `Iterables`) and only at the cost of an additional `if`-statement (hopefully).

**Comment by erezsh** [comment]
If I understand what you're suggesting, it won't work. Unlike the Transformer class, which is actually top-down, but emulate bottom-up using the stack, the LALR algorithm is actually bottom-up, so I don't see how exceptions could apply.

I'm also not sure about the utility of lazy generators, because usually users would want to scan every node at least once.

But maybe I'm missing something.

**Comment by erezsh** [comment]
Discard is now returned instead of raised (v1.0).
