### ISSUE TITLE
Document "maybe_placeholders"

### ISSUE THREAD

**Issue by erezsh** [lark-parser/lark#451]

**Comment by evandrocoan** [comment]
> Using `item?` will return the item if it matched, or nothing.
> 
> Using `[item]` will return the item if it matched, or the value `None`, if it didn't. It's possible to force `[]` to behave like `()?`, by using the `maybe_placeholders=False` option when initializing Lark.

I am not sure I understand this right. Why I would use `maybe_placeholders=True` with `[something]`, instead of `(something)?`

Can you give an usage example, i.,e., a grammar using `maybe_placeholders=False` versus `maybe_placeholders=True`?

**Comment by erezsh** [comment]
Because then, when you get the rule, you can predict the number of arguments.

For example, in the grammar

```ruby
arg: name [":" type]
```

You can then write in the transformer:

```python
    @v_args(inline=True)
    def arg(self, name, type):
        ...
```

And type may be `None`. If you used `?`, you would have to use `*args` to catch both cases.

**Comment by evandrocoan** [comment]
I am still a little lost. Then, I built two examples. 

The first uses `?`
```python
from lark import Lark, Transformer

class T(Transformer):
    def arg(self, *args):
        print('My args are', args)

parser = Lark("""
arg: name (":" type)?
name: "foo"
type: "bar"
""", start='arg', parser="lalr", transformer=T())

print('My tree is', parser.parse('foo'))
print('My tree is', parser.parse('foo:bar'))

# My args are ([Tree(name, [])],)
# My tree is None
# My args are ([Tree(name, []), Tree(type, [])],)
# My tree is None
```

And the second uses `arg: name [":" type]`
```python
from lark import Lark, Transformer

class T(Transformer):
    def arg(self, *args):
        print('My args are', args)

parser = Lark("""
arg: name [":" type]
name: "foo"
type: "bar"
""", start='arg', parser="lalr", transformer=T(), maybe_placeholders=True)

print('My tree is', parser.parse('foo'))
print('My tree is', parser.parse('foo:bar'))

# My args are ([Tree(name, []), None],)
# My tree is None
# My args are ([Tree(name, []), Tree(type, [])],)
# My tree is None
```

Comparing the outputs:
![image](https://user-images.githubusercontent.com/5332158/69013019-3e96d380-095a-11ea-82a5-939632a2b325.png)

 I see the first one on `parser.parse('foo')`, receives as first argument a list which has one Tree element. While the second `parser.parse('foo')` (using `maybe_placeholders`), also receives a list as argument, but it is a list with two elements instead of only one Tree element, and the last element is `None` instead of another Tree.

> And type may be None. If you used `?`, you would have to use `*args` to catch both cases.

But I am not using this `@v_args(inline=True)` thing. What magic it does? Looking at the implementation:
https://github.com/lark-parser/lark/blob/9727eb02264331b3771084ab58778dfbd7fff756/lark/visitors.py#L40-L41
It seems to take my children and expand them with `*` star. So will it make my decorated function to receive directly the trees instead of a list of threes? On this case I see why I would have to catch `*args`, instead of only `children`. So, `maybe_placeholders` is mostly useful only when using it with `@v_args(inline=True)`? May be include this to the `maybe_placeholders`docs then, to make they quite/pretty clear.
