### ISSUE TITLE
version 0.8.0 is not semver friendly

### ISSUE THREAD

**Issue by leff** [lark-parser/lark#515]
It says right in the description that it has breaking changes. 

> "Lark v0.8 - Big release, with some backwards-incompatible changes"

Breaking changes should bump the major version. This has real world consequences. For example, commentjson specifies lark-parser >== 0.7.1. Fresh installs of commentjson will pull in lark-parser v0.8.0 and I'm here to tell you that this breaks immediately.

See https://github.com/vaidik/commentjson/issues/32

I've worked around this for now by installing `lark-parser==0.7.8` before `commentjson` in my setup.py. (then spent a while getting all my coworkers and jenkins scripts upgraded)

**Comment by erezsh** [comment]
Sorry about that! Using a major release for such a small change seemed like an overkill, but I accept it was a misstep.

I reverted the change and released it as 0.8.1. We can consider it a bugfix.

P.S. It was an easy fix on your end, to create the parser with `Lark(..., maybe_placeholders=False)`

**Comment by leff** [comment]
Thanks, I'll check it out tomorrow when I'm back in the office.

For the record, I use lark only indirectly. I don't control commentjson, I just maintain an (internal) tool that relies on it. This is why it was difficult to just move forward.

**Comment by pkolbus** [comment]
Hi @erezsh, what you did in lark-parser is correct according to SemVer, prior to 1.0.0 anything can change at any time as the API is explicitly unstable. It’s commentjson not constraining the dependency correctly.

That said, thanks for reverting, as that will help until commentjson can fix things.

And since lark-parser is being used, please do consider defining an API and releasing 1.0.0 as soon as you’re ready to do so.
