### ISSUE TITLE
Standalone lexer: odd unexpected token error.

### ISSUE THREAD

**Issue by midoublelo** [lark-parser/lark#521]
I am developing a language using Lark but I am trying to implement if blocks that currently have an odd error. As it is hard to explain, here is an example:
```
if x > y: ## works
   var x = 5
end

if True: ## works
   var x = 5
end

if 5 > 3: ## doesn't work
   var x = 5 ## does not expect 'var'
end 
```

I get this error:
```
scanner.UnexpectedToken: Unexpected token Token(IDENTIFIER, 'var') at line 73, column 5.
Expected one of:
        * CHAR
        * __ANON_0
        * UINT128
        * INT32
        * __ANON_1
        * BOOL
        * STR
        * INT16
        * UINT16
        * UINT32
        * UINT64
        * INT64
        * INT8
        * INT128
        * UINT8
```
Obviously you need the grammar to know the error: https://github.com/jingle-lang/jingle/blob/master/source/scanner/scanner.lark

I have a feeling it is due to type annotations using colons the same way as the beginning of blocks but I'm not so sure as I cannot find anything explicitly causing it.

Any help would be very helpful,
Thanks!

Full test file: https://github.com/jingle-lang/jingle/blob/master/source/scanner/testfile.jn
Testing script: https://github.com/jingle-lang/jingle/blob/master/source/scanner/parser.py
Generated parser: https://github.com/jingle-lang/jingle/blob/master/source/scanner/scanner.py

**Comment by erezsh** [comment]
I didn't try it out, so maybe I'm wrong, but I think the problem is an ambiguity between the definition of a `block` and of `opt_vartype`.

I can suggest two options:

1) Change the syntax of vartype, maybe to `::`

2) Since your language seems to be newline oriented, you can require an explicit newline after `:` for blocks, in order to distinguish between the cases.

It's too bad Lark doesn't pinpoint the offending rules. Definitely something that needs improving.

**Comment by midoublelo** [comment]
Thanks for the very quick response!

I've changed the syntax of vartype to `::` and it works perfectly fine now. To be honest, I actually like the syntax of `::` more than just `:`, helps to differentiate between blocks and vartypes so thank you for that!

**Comment by erezsh** [comment]
Happy to help! :)
