### ISSUE TITLE
video tutorials or experience articles for beginners?

### ISSUE THREAD

**Issue by yuzhujiutian** [lark-parser/lark#528]
Where can I find lark video tutorials or experience articles for beginners?

I want to check the configuration of the project based on lark.

**Comment by erezsh** [comment]
I'm not a ware of video tutorials for Lark.

Have you read the JSON tutorial and the "How to write a DSL" articles? 

If you have, what sort of information is missing from them?

**Comment by yuzhujiutian** [comment]
Thank you for your reply. 

For example, I want to check the configuration shown in the figure. 
![image](https://user-images.githubusercontent.com/386347/75429477-d3ab5e80-5984-11ea-9aef-6ee7bcd56153.png)

After the coding is implemented, it is expected that multiple configuration files can be reused through the corresponding inspection rules configuration.

**Comment by erezsh** [comment]
Are you sure you need Lark? It looks like you can solve this with a simple regexp..

**Comment by yuzhujiutian** [comment]
Yes

1. Hope to lower the threshold for users. 
2. There is also a logical (+-* /) relationship check between cells in different excel profiles.

**Comment by erezsh** [comment]
I'm not entirely sure what you're trying to do, or what's the difficulty you're encountering.

I'll try to give a short outline based on what I've seen, so we can build on that.

You have different sorts of constraints that you need to apply to some text. Some are syntactic (and context free), while some are value-based. 

You can use Lark to parse and verify the syntactic constraints, and then use a transformer to validate the values.

You should do each one in a different rule, so that you can tell which path was taken at the end of the parse. You can also use the `start` parameter to pick which one to start from (in case you know what type that expression should be).

Is that enough to get you started?

**Comment by yuzhujiutian** [comment]
Thank you very much!

I will first try to use the regular expression you mentioned above, and then try to implement it based on lark.
