### ISSUE TITLE
AssertionError when packaging with pyinstaller

### ISSUE THREAD

**Issue by zurgeg** [lark-parser/lark#548]
For some reason, any program using lark will crash with an assertionerror when it is frozen. Am I supposed to use a different packaging tool or something? Can you help?
Thanks in advance.

**Comment by MegaIng** [comment]
Could you maybe give as the full exception with stack trace (as much as you can see)? And a workaround could be generating a standalone parser and putting that in the pyinstaller.

**Comment by MegaIng** [comment]
Ok. Why did you not link https://github.com/pyinstaller/pyinstaller/issues/4776? That would greatly helped.

You managed to trick the system: It tries to find that file, and then calls `open(path)` to created the correct error message- which success, since `common.lark` is in the CWD. Then t calls `assert False` to make sure it actually terminates. For the moment, you can either change your grammar to `%import .common.<...>`. I will see later today what can be done the fix this.

**Comment by MegaIng** [comment]
The better why to solve this problem is with a simple import hook: (If I understand PyInstaller correctly)

Create a `hook-lark.py` file with the following content:

```python
from PyInstaller.utils.hooks import collect_data_files

datas = collect_data_files('lark')
```

Make sure this is 'in a place where PyInstaller searches for hooks'. I guess this would be the CWD and the `PyInstaller/hooks` directory.

**Comment by erezsh** [comment]
@zurgeg What version of Lark is this?

`lark.Parser` isn't even a valid class.

**Comment by zurgeg** [comment]
Oh, wait. I meant ```lark.Lark```.

**Comment by zurgeg** [comment]
I also think from the pyinstaller issue that we should change the import name to ```lark-parser``` so we can PR to pyinstaller to have a permanent fix for this.

**Comment by erezsh** [comment]
`lark-parser` is not a legal name to import.

**Comment by erezsh** [comment]
Why do they need a different name?

**Comment by MegaIng** [comment]
Look at https://github.com/lark-parser/lark/issues/505 for the reasones why we wont change the import name. (I fully agree with @erezsh)

The problem with the import name clash is that PyInstaller's hook files (files that describe how to import files/ which additional files need to be included in the final package) are of the form `hook-{import name}.py`. This will obviously be the same for `lark-parser` and `lark`. This would prevent it from being included in PyInstaller default hooks, since we couldn't guarantee that the lark that is used is always this lark.

**Comment by zurgeg** [comment]
Or we could just use lark_parser instead of lark-parser.

**Comment by zurgeg** [comment]
I think lark is still maintained. I have opened an issue on their repo telling them to change their name.

**Comment by zurgeg** [comment]
I'm also guessing since your repo is used by more and the chances that the person uses both ```lark-parser``` and ```lark``` (is 1. impossible and) is very low. I think we should put in the lark-hook.py file.

**Comment by erezsh** [comment]
So, where are we on this? Was the problem solved?

**Comment by zurgeg** [comment]
Yes, this problem has been solved.

**Comment by erezsh** [comment]
Excellent!
