### ISSUE TITLE
Parser creation does not end

### ISSUE THREAD

**Issue by handras** [lark-parser/lark#566]
**Describe the bug**

I am trying to create a DBC file parser. The parser creation step does not finish in a timely manner and uses too much RAM (more than 30 minute and 8 Gb).

**To Reproduce**

I have reduced to problem to only one rule and simplified it. (In practice this is the symbol definition in the DBC) Try the following script:

```
from lark import Lark

grammar="""
start : [ "a" ["b"]  ["b1"]  ["b2"]  ["b3"] ["c"]  ["c1"]  ["c2"]  ["c3"] ["d"]  ["d1"]  ["d2"]  ["d3"] ["e"]  ["e1"]  ["e2"]  ["e3"] ["f"]  ["f1"]  ["f2"]  ["f3"]]
"""
parser = Lark(grammar, parser='lalr', lexer='contextual')
```

**Comment by MegaIng** [comment]
This is not a bug, but the expected behavior. Internally, your nice human understandable EBNF grammar gets turned into easy to optimize and fast BNF grammar. This step includes maybe expansion:

```
start: "a" ["b"]
```
becomes
```
start: "a"
     | "a" "b"
```
and
```
start: ["a"] ["b"]
```
becomes
```
start: 
     | "a"
     | "a" "b"
     | "b"
```
which means that every maybe in a single rule doubles the number of expansion that are generated. You have 21 maybes, which means 2**21 = 2,097,152 expansions. This takes a lot of time, and a lot of memory to process.

Solution: Don't have many maybes in a single rule. Split them up:

```
start : [ "a" b c d e f ]
b: ["b"]  ["b1"]  ["b2"]  ["b3"]
c: ["c"]  ["c1"]  ["c2"]  ["c3"]
d: ["d"] ["d1"]  ["d2"]  ["d3"] 
e:  ["e"]  ["e1"]  ["e2"]  ["e3"]
f:  ["f"]  ["f1"]  ["f2"]  ["f3"]
```
or even, if you truly want them all in one tree in the result:
```
start : [ "a" _b _c _d _e _f ]
_b: ["b"]  ["b1"]  ["b2"]  ["b3"]
_c: ["c"]  ["c1"]  ["c2"]  ["c3"]
_d: ["d"] ["d1"]  ["d2"]  ["d3"] 
_e:  ["e"]  ["e1"]  ["e2"]  ["e3"]
_f:  ["f"]  ["f1"]  ["f2"]  ["f3"]
```

**Comment by MegaIng** [comment]
This is the central issue for this: #506

**Comment by handras** [comment]
Thank you for the explanation. Indeed with the suggest modification it is now working.
