### ISSUE TITLE
Turning Lark into a modularized mutli-paradigm parsing toolbox

### ISSUE THREAD

**Issue by phorward** [lark-parser/lark#588]
Hi there!

Since a long time, I have the dream of an ultimate toolbox for all parsing-related stuff, which fits all my needs and can be used for any parsing-related issue, including experimentation.

The main goals of my dream are:
1. Write a grammar once in one kind of EBNF-language
2. Use a parser generated from this grammar in several target languages and technologies (for me, it currently is C, Python and Rust)
3. Work with AST traversals instead of semantic code attached to the grammar
4. Combine different scanners (Pythons `re`, self-contained DFA), but also support of scanner-less parsing
5. Use the same toolbox for experimentation and fiddling with algorithms and ideas

Right now, I'm experimenting with the GLL parsing algorithm, but with the need to not completely rewrite all my grammars again, and with the need to use the resulting parser in Python and Rust. Therefore, I'm currently undetermined whether I write another tool on my own or modify an existing tool, like Lark.

While taking a look into Larks source code and documentation, I found out that there are [plannings](https://github.com/lark-parser/lark/blob/master/docs/features.md#planned-features-not-implemented-yet) to generate code in other languages and implement an own DFA construction for lexical analysis without using Pythons regex-module for this. For me, the construction of scanner-less parsers is also an important thing which should be supported. This could be done by breaking up the regular expressions and turning them into a part of the grammar, obviously a process of grammar rewriting which might be done internally, including whitespace insertion.

All these targets could only be achieve when Lark is broken up into a modular, plugin-based design, where different parser generators, different scanner generators and different code generators are stacked together, and Lark itself only serves as the core to handle and rewrite grammars and use the plugins attached. I've noticed that Lark already has a modular structure, but my concept would be to separate all these modules and make them entirely plug-able and replaceable.

This is my first draft of an idea how this could look like:
![lark-modularized](https://user-images.githubusercontent.com/16870072/81807232-042f7d00-951e-11ea-88e9-739cfa62caa0.png)

Please don't feel offended or worried, I don't want to break Lark's current structure or principles with this draft. It is only a proposal of what might be done, and I'm very interested into what your future plans for Lark are. I need a little decision help, whether my concept could become a part of Lark, or if I have to do it on my own.

For now, I am not using Lark for my projects, because it does not fit into my requirements. But it could do so when some features would be supported. Python as implementation language for this toolbox is absolutely the right tool. Code generation could be done easily using template engines and a serialized structure of the generated parse-tables for each Parser module. The generated parsers generally should support the features of their implementation language for sake of performance, but should share the same node structuring for resulting tree traversals and semantic evaluation. For sure, features like the contextual lexer in the LALR(1) parser generator should be possible, also in the generated result code.

What are your opinions on this proposal?

Edit: Updated diagram (the core component features) and added a note on the contextual lexers.

**Comment by erezsh** [comment]
Hi Jan!

My goals are very similar to those that you listed, and I would say Lark satisfies all of them, to some degree.
Lark can already generate a LALR parser in Julia. Lark also used to have support for scannerless parsing in Earley, which involved rewriting the strings as a list of character terminals. I decided to remove it because dynamic lexing was just as capable and is significantly faster. But I'll consider bringing it back if there's a good reason.

If you want to contribute a GLL parser to Lark, I'll be happy to help as much as I can.

Same if you want to contribute a Rust parser generator.

Regarding lexical analysis, we have made some progress in that area too. The idea was to detect collisions in regexps by intersecting them: https://github.com/MegaIng/interegular
That reminds me, @MegaIng, why didn't we move forward with that? Did you ever submit a PR, or were there still some performance issues?

I'm not at all offended by the diagram, it seems like you have the right idea, in theory. I'm not sure it would hold up in practice. I would say all the modules in Lark are already pluggable. The standard lexer can serves both LALR(1) and Earley. But each one also has specialized lexers which only fit itself, and I don't see how that could change.

To summarize the problem more abstractly: Each parser has its own unique configuration and abilities, and I don't think it's possible to know them in advance and pre-expose the right interface. The obvious solution would be to expose all the information, but that would actually make it less modular.

So what I've done so far is to abstract only as much as necessary to support the algorithms that I have, and I'll be happy to keep abstracting whenever necessary, as long as it actually makes the code better.

Having said that, it's possible that I've overlooked things, so I'm open to hear another plan of action. And of course there's always room for improvement.

Regarding templated parsers, I think it's a good idea, in theory. I don't know how easy it would be to write a lexer+parser+treebuilder like that for each target. Especially if we want it to support the contextual lexer, and all the tree manipulation logic that the grammar allows.

At any rate, Lark already knows to create a JSON of everything that it analyzed, so applying to a template should be fairly easy.

So bottom line, I like it. I want to see Lark grow, and I think those are good directions for it to go in. So if you want to use Lark, I'm absolutely for it, as long as you submit clean and modular code. (I have to set a standard to keep it maintainable!)

Let me know what you think, and if you have more questions for me.

**Comment by phorward** [comment]
Hi Erez,

thank you for your detailed answer and assessments on my proposal, and I'm very sorry for my delayed answer. Due current business projects among other things, I have less time to work on Lark and parsing projects.

I think, the very first, I have to get deeper into Lark's source code, some relationships and algorithms are not clear to me right now. But I think, personally for me, it's best to do further developments within this project in future, rather then something I create on my own.

For me, the first glimpse of the code was, that things are not separated the way like I would have done it, but I think I just need more exploration on it to manifest my view, and maybe I then might do some restructuring, or even understand why you built it this way.

> Lark can already generate a LALR parser in Julia. Lark also used to have support for scannerless parsing in Earley, which involved rewriting the strings as a list of character terminals. I decided to remove it because dynamic lexing was just as capable and is significantly faster. But I'll consider bringing it back if there's a good reason.

OK cool! What do you think of scannerless LALR? Therefore, the parts of the grammar rewriting need to be part of Lark itself and some scannerless-mode where parsers are rewritten apart of the underlying parser mode. Surely, in case an naive LL parser target is used, repetitions need to be made right-recursive, or there must be a memoization algorithm...

> If you want to contribute a GLL parser to Lark, I'll be happy to help as much as I can.

Sure, when I finished with my exploration of that algorithm - I've just recently started. I'm not that familiar with parse forest for now. But I also think I first need to implement it in a smaller, more manageable project for a better understanding, just for myself.

> Same if you want to contribute a Rust or C parser generator.
OK, this is achievable. Is there a preferred way how this should be implemented? I could serve a template language that I wrong on my own, but currently using my own parser generator [UniCC](https://github.com/phorward/unicc). To underline Larks usability, it would be better to first implement this template language entirely in Lark. Or might you prefer an existing language, like Jinja2? (I don't like it that much, my attempt, its currently called [vistache](https://github.com/phorward/viur-logics/tree/pyodide#vistache-a-logics-powered-template-language) and inspired by Mustache, is easier for code generation tasks. I did [some tests](https://github.com/phorward/unicc/blob/unicc2-codegen/rust.rs) on it in my UniCC² repository with Rust, but abandoned for now, because I think it's a waste of time to continue the C-based UniCC where I might spend this time into a huger project like Lark. In the last link, you find Vistache template code that is configured to be used as Rust-comments using `/*(on...)*/.../*(or...)*/.../*(go)*/` constructs to build loops and output code, but still remain inside Rusts syntax, so highlighting with an arbitrary editor works well.

> To summarize the problem more abstractly: Each parser has its own unique configuration and abilities, and I don't think it's possible to know them in advance and pre-expose the right interface. The obvious solution would be to expose all the information, but that would actually make it less modular.

Well, here it might be useful to first provide a grammar toolbox to built any grammars (including those scanner-less ones, I'm fascinated of them ;-)) which then can be fed to *any* parser backend or parser code generator backend.

For example, the grammar toolbox as Lark's front-end may already compute all FIRST, FOLLOW and SELECT-sets (for table-driven LL) and mark left-and right-recursions. Even all things that are required by some parser generator, merged into one tool that already pre-computes all analyses necessary on the grammar and their symbols.

A parser backend, which then does not support e.g. left-recursion, might report an error then, but it also might rewrite the grammar in this case to make it working also in the target algorithm.

Even if these sets and values are not required, I think for the reason that Lark is written in Python, it does not need to be fast or efficient when used just as the generator and toolbox But the result, which is a re-usable parser object or generated source code, then is fast and efficient because it only uses the stuff which is already there or was generated.

*smile* hehe, I just got the idea of building one pre-computed grammar and then feeding it to multiple backends, to quickly find out which parsing algorithm is the fastest for a specific grammar *grin*... that might be useful for some users as well!
> So bottom line, I like it. I want to see Lark grow, and I think those are good directions for it to go in. So if you want to use Lark, I'm absolutely for it, as long as you submit clean and modular code. (I have to set a standard to keep it maintainable!)

Sure, and I think Lark is great base for this. I'm aware that Lark has an already a huge and in some detail parts very skilled code base (for some algorithms, I first need to look them up and dive into them, and that's a time problem, though!), but generally I would like to contribute.

Feel free to close the issue, or we can continue some discussion here.

Best regards

Jan

**Comment by phorward** [comment]
Hey there, to keep issues low I now decided to close this here for now. Due to other, personal projects, I currently have too less time to participate and provide code to Lark, but I'll stay tuned about further developments in here and try to help when possible.

**Comment by erezsh** [comment]
Hi, it seems like I should have replied here, sorry that it slipped my mind!

It's perfectly understandable, I have my own personal projects going. If you ever want to come back and contribute to Lark, I'll be happy to help you do that.

P.S. I don't think a scannerless LALR(1) is a good idea. I think they ideal algorithm will try a regexp, and default to scannerless, and in the same sense will try LALR(k), and default to Earley only when needed.

In theory, these different layers can be written in different languages (well, regexps already are).

However, such a layered parser is hard to write. But Lark is going in that direction, and the suggestions you proposed might push it even further there. So I definitely dig that direction.
