### ISSUE TITLE
Incorrect Expected Token

### ISSUE THREAD

**Issue by MegaIng** [lark-parser/lark#646]
In the list of Expected Tokens of the `UnexpectedToken`, some tokens appear that aren't valid

```python

from lark import Lark, Token

grammar = """
start : term ";"
term : "a"
      | "(" term ")"
"""

parser = Lark(grammar, parser='lalr')  # lark parser

parser.parse("(a")
```

raises

```
Traceback (most recent call last):
  File "C:\Users\tramp\PycharmProjects\lark\lark\parsers\lalr_parser.py", line 60, in get_action
    return states[state][token.type]
KeyError: '$END'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/tramp/PycharmProjects/lark/test.py", line 106, in <module>
    parser.parse("(a")
  File "C:\Users\tramp\PycharmProjects\lark\lark\lark.py", line 400, in parse
    return self.parser.parse(text, start=start)
  File "C:\Users\tramp\PycharmProjects\lark\lark\parser_frontends.py", line 127, in parse
    return self._parse(token_stream, start, set_parser_state)
  File "C:\Users\tramp\PycharmProjects\lark\lark\parser_frontends.py", line 58, in _parse
    return self.parser.parse(input, start, *args)
  File "C:\Users\tramp\PycharmProjects\lark\lark\parsers\lalr_parser.py", line 36, in parse
    return self.parser.parse(*args)
  File "C:\Users\tramp\PycharmProjects\lark\lark\parsers\lalr_parser.py", line 112, in parse
    _action, arg = get_action(token)
  File "C:\Users\tramp\PycharmProjects\lark\lark\parsers\lalr_parser.py", line 67, in get_action
    raise UnexpectedToken(token, expected, state=state, puppet=puppet)
lark.exceptions.UnexpectedToken: Unexpected token Token($END, '') at line 1, column 2.
Expected one of: 
	* SEMICOLON
	* RPAR
```
Despite `SEMICOLON` not being valid.

Same behavior for `puppet.choices()`

**Comment by erezsh** [comment]
So, I'll try to explain why this happens.

The LALR stack looks a little like a regular call stack, where each rule is a function that can call other rules. Whenever a rule finishes (meaning, all their items are satisfied), it returns up the stack to its parent and continues from where it stopped.

However, there's a little problem, because LALR(1) needs to always have a lookahead to proceed, and when you are at the end of the rule, there are no more symbols to test against.

So, the obvious solution is to read the lookahead by looking at the parent rule that called this rule. But, at the time that the LALR parse-table is generated, that is not known. And so the solution is to take the lookahead after each and every place where the rule can be called, i.e. to sum up all.

**Comment by erezsh** [comment]
Well, after this long preamble, we do have all the information necessary at run-time, so it probably shouldn't be too hard to provide with a more accurate list.

**Comment by erezsh** [comment]
The simplest way that I can think of is to actually step through each of these terminals using the puppet, and see which ones the parser accepts, vs. throws an exception.

**Comment by MegaIng** [comment]
I was half aware of this, but I wasn't quite sure how exactly it worked. Are you trrying to implment this? Or should I try?

**Comment by erezsh** [comment]
If you want to try it, go ahead. It shouldn't be too hard.

Otherwise I'll do it.

I wouldn't change expected, but maybe we can call it `expected_verified`, or `accepts`.

**Comment by erezsh** [comment]
Thanks!
