### ISSUE TITLE
Understanding "Lexer does not allow zero-width terminals."

### ISSUE THREAD

**Issue by dsuch** [lark-parser/lark#649]
Hello,

I am not quite sure what the significance of this message is **Lexer does not allow zero-width terminals.** In Lark 0.9.0 it is raised by ```TraditionalLexer.__init__:L311``` - can you help me out with it?

This happens, for instance, with a grammar such as here:

```
any_space: / */
start: any_space
```

The above is a simple grammar extracted out of a larger one solely to reproduce that exception.

Same goes for this one:

```
any_space: / */
my_root: "abc" any_space
start: my_root
```

But not for this one:

```
ANY_SPACE: / */
MY_ROOT: "abc" ANY_SPACE
start: MY_ROOT
```

I understand what this message says literally but I do not understand why it works the way it does, particularly because I am indeed interested in using rules rather than terminals in this part of the grammar which is how I noticed this behaviour in the first place.

In fact, I commented out this particular check right in TraditionalLexer's source code and I did not notice any other pieces of Lark malfunctioning. That is what makes me wonder what logic depends on the assumption expressed in this assertion:

```python
if t.pattern.min_width == 0:
    raise LexError("Lexer does not allow zero-width terminals. (%s: %s)" % (t.name, t.pattern))
```

Thanks.

**Comment by MegaIng** [comment]
```
ANY_SPACE: / */
MY_ROOT: "abc" ANY_SPACE
```
This doesn't actually create two tokens, but one: `ANY_SPACE` is implicitly merged into `MY_ROOT` and only one (now non-empty) regex is used.

The problem with zero width terminals is the following:

```
start: E*
E: / */
```
what output should this grammar produce?
```
start
```
or
```
start
    E
```
or
```
start
    E
    E
```
or
```
start
    E
    E
    E
    E
    E
    E
    E
    E
    E
```
and there is a really simple fix:
any_space: / +/?
my_root: "abc" any_space
start: my_root

**Comment by erezsh** [comment]
So, let's disable this limitation, and look at this little example:

```python
from lark import Lark
l = Lark('start: /a?/ /b?/')
l.parse('a')
```

In terms of the parser, here is how the grammar looks:

    start: MAYBE_A  MAYBE_B

So after matching `MAYBE_A`, the parser expects another terminal of `MAYBE_B` to arrive. But the lexer has already finished its work, and has no reason to send anything over. The lexer also doesn't know the parser expects anything (for example, for the standard lexer).

This could potentially be solved by treating it as a special-case and marking those empty terminals for the parser, making complicated code even more complicated.

But disallowing it seems much simpler, especially since this feature is in no way necessary.

**Comment by dsuch** [comment]
Thank you both for the comprehensive answers - I was not aware of these details of the lexer-to-parser interplay before but everything is clear now!
