### ISSUE TITLE
Possible optimization?

### ISSUE THREAD

**Issue by pwwang** [lark-parser/lark#699]
https://github.com/lark-parser/lark/blob/7c8d6ee787692f7287d38de92d06174bf956d72a/lark/lexer.py#L193
to
```python
lenstream = len(stream)
while line_ctrl.char_pos < lenstream:
  ...
```

```python console
In [1]: stream = ' ' * int(1e6)                                                                                    

In [2]: %timeit for _ in range(int(1e6)): len(stream)                                                              
71.9 ms ± 3.54 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [3]: lenstream = len(stream)                                                                                    

In [4]: %timeit for _ in range(int(1e6)): lenstream                                                                
30.7 ms ± 853 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by erezsh** [comment]
Yep. I'm not sure it will be noticeable in a real task though.

**Comment by LudwigCRON** [comment]
I have some file ranging from 20MB to 180MB to be parsed. In my checks, I added some timing information about the time to load the file content as text and the time to parse the content (average results of 10 measurements).
Without any change
```
test_fanout (__main__.TestLiberty) ... ok
test_lut (__main__.TestLiberty) ... 
[INFO] Read file in 0.014034 ms
[INFO] Parse file in 1.7023849999999998 ms
ok
test_number_parsing (__main__.TestLiberty) ... ok
test_property_parsing (__main__.TestLiberty) ... 
[INFO] Read file in 0.012140999999999999 ms
[INFO] Parse file in 0.931928 ms
ok
test_samsung (__main__.TestLiberty) ... 
[INFO] Read file in 99.75262599999999 ms
[INFO] Parse file in 10518.726369 ms
ok
test_samsung_ccs (__main__.TestLiberty) ... 
[INFO] Read file in 1000.2684059999999 ms
[INFO] Parse file in 124208.195123 ms
ok
test_xfab (__main__.TestLiberty) ... 
[INFO] Read file in 20.873761 ms
[INFO] Parse file in 17769.545948 ms
ok
```
After the change but setting the text's length as a property of LexerState to have
```python3
while line_ctrl.char_pos < lex_state.text_length:
```
I got the following result
```
est_fanout (__main__.TestLiberty) ... ok
test_lut (__main__.TestLiberty) ...
[INFO] Read file in 0.011715 ms
[INFO] Parse file in 1.416472 ms
ok
test_number_parsing (__main__.TestLiberty) ... ok
test_property_parsing (__main__.TestLiberty) ...
[INFO] Read file in 0.011592 ms
[INFO] Parse file in 0.9002509999999999 ms
ok
test_samsung (__main__.TestLiberty) ...
[INFO] Read file in 99.041482 ms
[INFO] Parse file in 11047.85023 ms
ok
test_samsung_ccs (__main__.TestLiberty) ...
[INFO] Read file in 1003.916072 ms
[INFO] Parse file in 88897.636579 ms
ok
test_xfab (__main__.TestLiberty) ...
[INFO] Read file in 25.165672999999998 ms
[INFO] Parse file in 12977.109668 ms
ok
```
Therefore, the time spent in computing the text length does not have much of an impact on small to medium file size. Over a large file (~3 million of line and ~180MB) this starts to be noticeable 30 seconds are saved. Not sure there is plenty of such case in the wild.

**Comment by erezsh** [comment]
@LudwigCRON Are you suggesting that `len()` is affected by the length of the file?

**Comment by LudwigCRON** [comment]
`len()` indeed depends on the length of the file. The content of the file is stored in memory and one should go through the complete array of memory storing the content to get the length. So it is normal to have such a relation. And as the computation is performed at each `lexer.next_token()` call, the timing impact is more relevant for big file than for small files.

**Comment by MegaIng** [comment]
@LudwigCRON No, `len()` is constant in CPython: https://stackoverflow.com/questions/1115313/cost-of-len-function

**Comment by LudwigCRON** [comment]
@MegaIng is right. So the delta is due to the time to call built-in function + time to fetch the address of `str` object compared to time fetch `Py_size_t` directly ?

**Comment by erezsh** [comment]
Hard to tell, but it seems a bit big just for a function call.

How many times did you run your benchmark? Have you tried reversing the order of execution? (to negate effects of caching)

**Comment by LudwigCRON** [comment]
I re-executed the tests today on the server with CPython 3.9.5 (as previously)

To gives you an idea of how long files are here is the number of lines per files
| file tested | number of lines | file size |
|:--------------|---------------------:|-----------:|
| lut             | 5 | 271 B |
| property   | 12 | 248 B|
| samsung | 386466 | 17.37 MB |
| samsung ccs | 2911659 | 161.82 MB |
| xfab | 386490 | 19.95 MB|

the tests are repeated 8 times and in `Lark(..., cache=False)` and before launching with and without the modification the `__pycache__` folder in the site-packages and the folder is removed. In addition to the previously posted result, I added in the unittest setup a modification to introduce random order [sortTestMethodUsing](https://docs.python.org/3.9/library/unittest.html#unittest.TestLoader.sortTestMethodsUsing)To reduce the effect of loading during the execution of the tests I prepend the command with `nice -n -10`

| file tested | repeat index | parsing time without modification | parsing time with modification  |
|:--------------|:----------------:|------------------------------------:|--------------------------------:|
| lut | 1 | 2.065 ms | 2.838 ms|
| property | 1 | 1.528 ms | 1.029 ms|
| samsung | 1 | 9939.34 ms | 10876.721 ms|
| samsung ccs | 1 | 87216.030 ms | 90311.498 ms |
| xfab | 1 | 11589.092 ms | 13160.595 ms |
| lut | 2 | 0.868 ms | 0.801 ms |
| property | 2 | 1.410 ms | 1.443 ms |
| samsung | 2 | 10514.588 ms | 10909.170 ms |
| samsung ccs | 2 | 90687.589 ms | 89531.908 ms |
| xfab | 2 | 11720.620 ms | 12815.926 ms |
| lut | 3 | 0.942 ms | 2.007 ms|
| property | 3 | 1.197 ms | 1.145 ms |
| samsung | 3 | 11026.663 ms | 11680.462 ms|
| samsung ccs | 3 | 89870.610 ms | 92590.075 ms |
| xfab | 3 | 12756.738 ms | 11967.613 ms |
| lut | 4 | 1.288 ms | 0.907 ms |
| property | 4 | 0.720 ms | 0.639 ms |
| samsung | 4 | 10991.675 ms | 11995.332 ms |
| samsung ccs | 4 | 85241.648 ms | 92300.433 ms |
| xfab | 4 | 11880.307 ms | 12403.755 ms |
| lut | 5 | 1.327 ms | 1.192 ms|
| property | 5 | 0.773 ms | 0.742 ms |
| samsung | 5 | 11603.420 ms | 10520.835 ms |
| samsung ccs | 5 | 89800.800 ms | 87888.244 ms |
| xfab | 5 | 12019.628 ms | 12431.530 ms |
| lut | 6 | 1.644 ms | 0.843 ms |
| property | 6 | 0.796 ms | 0.770 ms |
| samsung | 6 | 10533.291 ms | 12282.484 ms |
| samsung ccs | 6 | 90236.499 ms | 89993.602 ms |
| xfab | 6 | 12783.144 ms | 13991.512 ms |
| lut | 7 | 1.926 ms | 1.676 ms |
| property | 7 | 2.650 ms | 1.108 ms |
| samsung | 7 | 12011.010 ms | 13021.039 ms |
| samsung ccs | 7 | 93283.432 ms | 91321.168 ms |
| xfab | 7 | 14007.847 ms | 11923.525 ms |
| lut | 8 | 3.594 ms | 0.810 ms |
| property | 8 | 2.175 ms | 1.227 ms |
| samsung | 8 | 11067.004 ms | 12386.96 ms |
| samsung ccs | 8 | 87982.380 ms | 97362.564 ms |
| xfab | 8 | 12781.353 ms | 13244.068 ms |

The big difference is no more seen. Thus I assume the difference seen can be due to the load on the server and potential caching effect.

**Comment by pwwang** [comment]
Questions:
1. Looks like larger files took longer (slightly, though) with modification, not making sense to me.
2. Why aren't the following neat tests simple and intuitive to tell the difference without other potential effects? `Lark(...)` involves a lot of procedures that may override the difference between with/without modification, even though the difference could be (and looks like it is) one of the tiniest of all procedures.

```python console
In [1]: stream = ' ' * int(1e6)                                                                                    

In [2]: %timeit for _ in range(int(1e6)): len(stream)                                                              
71.9 ms ± 3.54 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [3]: lenstream = len(stream)                                                                                    

In [4]: %timeit for _ in range(int(1e6)): lenstream                                                                
30.7 ms ± 853 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by erezsh** [comment]
Thanks Ludwig! I'll close this now unless someone's benchmark shows otherwise :)

@pwwang Personal computers usually aren't tuned for benchmarking. There's random processes popping up, the cpu may change speed according to temperature, and other such pitfalls. I would guess that many of the differences are due to such random circumstances.
