### ISSUE TITLE
Add documentation for LALR and EARLY’s differences

### ISSUE THREAD

**Issue by ThatXliner** [lark-parser/lark#732]
**Suggestion**
I would like some documentation on LALR and EARLY’s differences and how/why is EARLY more flexible.

**Describe alternatives you've considered**
I could have searched a Wikipedia article but it’s pretty long and boring (the documentation was more fun to read).

**Additional context**
Maybe a chart of all the differences and similarities EARLY, LALR, and CYK have in common, not just an article/page.

**Comment by erezsh** [comment]
Can you explain what's missing from https://lark-parser.readthedocs.io/en/latest/parsers.html ?

I can't think of a way to put it in a chart, that will actually make it clearer.

Earley supports all context-free grammars. Is slow. (Includes ambiguous and nondeterministic grammars.)

LALR supports a small subset of context-free grammars. Is fast. (No support for ambiguous and nondeterministic grammars, among other limitations).

I can't think of a more detailed way to explain the difference.

**Comment by ThatXliner** [comment]
Maybe an example of a grammar that's only earley and a grammar that's also LALR

**Comment by erezsh** [comment]
*Every* LALR grammar is also an Earley grammar.

`examples/fruitflies.py` is an Earley only grammar.

Is that helpful?

**Comment by ThatXliner** [comment]
So only Earley can handle ambiguity?

**Comment by MegaIng** [comment]
In general yes. There are a few subtle things that LALR can't handle in addition to that. Earley is an algorithm that just works™, but it is slow. It can handle arbitrary ambiguities. This means it can handle any Language you can express with EBNF.

LALR on the other is a lot more restrictive. For the exact restrictions, there are multiple books you could read.

In general LALR fails with any ambiguities (those hat it can detect will fail at Parser build time. This is impossible in general, otherwise you would have solved the halting problem. Others will just lead to unexpected results.)

Since we are implementing a LALR(1) parser, LALR also fails with any situation where looking at the next token isn't enough to decide which rule to reduce.

**Comment by erezsh** [comment]
Technically speaking, LALR(1) cannot parse any grammar that is non-deterministic with a lookahead of 1 token (that includes ambiguous).

Our implementation does slightly better than Yacc's, but this limitation is inherent to LALR.

**Comment by ThatXliner** [comment]
In conclusion, if a grammar cannot decide which path it should take just by looking at the next token, it's not LALR

**Comment by erezsh** [comment]
Not LALR(1), yes. In theory, there can also be a LALR(k) implementation somewhere.

**Comment by ThatXliner** [comment]
Got it
