### ISSUE TITLE
puppet not available on_error

### ISSUE THREAD

**Issue by fabioz** [lark-parser/lark#733]
**Describe the bug**

I'm trying to handle errors in my grammar, but it seems that the available support just isn't there in some cases (sometimes `e.puppet` is there and sometimes it isn't).

**To Reproduce**

I'm attaching a file with the contents to reproduce (note that the grammar is still in development, but still, error handling doesn't really seem to work depending on the place that the error is thrown internally -- i.e.: errors in `lark.lexer.ContextualLexer.lex` and `lark.lexer._Lex.lex` don't seem to be recoverable).

Example showing `e.puppet = None`: [test_lark.py.txt](https://github.com/lark-parser/lark/files/5445243/test_lark.py.txt)

Note: I effectively need a way to handle any error (my final target is a grammar to be used in a language server, where it would be used for code-completion... having a grammar without error handling isn't very useful in this situation as many times users may be in an inconsistent state when code-completion is requested). From the docs I thought this would be possible (https://lark-parser.readthedocs.io/en/latest/examples/advanced/error_puppet.html)... am I missing something?

**Comment by MegaIng** [comment]
Are you using the current master?

In general: the puppet is there when it is an actual problem with the parser, and will not be there when it is a problem with the lexer. This is most often the divide between `UnexpectedToken`/`UnexpectedCharacter`.

But there is some smartness that at the same time reduces and increases confusion. When the `ContextualLexer` hits an unexpected characters it checks whether or not it knows any Terminal (even if it is not valid right now.) and itself raises an `UnexpectedToken` error. This will not have the `puppet` attribute, since the parser isn't raising the exception. (But I think the current master has a fix for this)

In regard to a language server: There is an ongoing effort over at [lark-parser](lark-language-server) to build a general system to easily create lsps from lark grammars.

**Comment by erezsh** [comment]
The short answer, is it should work on the `master` branch.

**Comment by fabioz** [comment]
I wasn't using the `master` branch. I'll close this then, thanks.
