### ISSUE TITLE
Bug in Earley parser when there is ambiguity in empty rules

### ISSUE THREAD

**Issue by erezsh** [lark-parser/lark#741]
**Describe the bug**

The Earley parser creates an incorrect tree

**To Reproduce**

```python
from lark import Lark
grammar = """
a: _x
_x: _x? b
b:
"""

p = Lark(grammar, start='a', ambiguity='explicit')
```

This will throw an `IndexError` because the wrong node constructor gets called.

The non-expanding variation doesn't throw an error, but creates a non-sensical result:

```python
from lark import Lark
grammar = """
a: x
x: x? b
b:
"""

p = Lark(grammar, start='a', ambiguity='explicit')
print(p.parse('').pretty())
```

Output
```python
a
  _ambig
    x
      b
    x
      b
```

Earlier versions of Lark throw `ParseError: Infinite recursion in grammar!`, which is technically more correct, although not very useful either.

**Comment by chanicpanic** [comment]
Both cases generate the same SPPF.

![image](https://user-images.githubusercontent.com/51764816/97844588-2c639180-1ca0-11eb-9fbe-ce157f0e06dc.png)

The (x, 0, 0, -inf) node has two children, so that gives the two derivations. However, the left child leads to a cycle. In the current implementation, the (x ::= x*b, 0, 0, -inf) node will be discarded which results in the unexpected number of children in the node constructor. I think the desired behavior would be for the (x, 0, -inf, 0) node to be discarded instead. I can work on this issue and improve the handling of SPPF cycles.

**Comment by erezsh** [comment]
>  I can work on this issue and improve the handling of SPPF cycles.

@chanicpanic I would appreciate that!

**Comment by erezsh** [comment]
Good job!
