### ISSUE TITLE
Unexpected behavior on "binary operation"

### ISSUE THREAD

**Issue by scratchmex** [lark-parser/lark#813]
**What is your question?**

I'm getting some unexpected token parsed on this simple grammar. I hope you can explain why this behavior occurs.

**grammar**:
```lark
?start: term

?term: DOTS | (term SUM term)

DOTS: "."+
SUM: "+"
```

Explain what you're trying to do, and what is obstructing your progress.
Go on the [online IDE](https://lark-parser.github.io/lark/ide/app.html) and try with the following set of inputs:
```
.+.+.
.+.+..
.+.+...
.+.+....
```

As you will see, the tokens keeps alternating between the following token tree:
- term
  - .
  - \+
  - term
    - term
      - .
      - \+
      - {{ n number of dots }}

and

- term
  - term
    - .
    - \+
    - .
  - \+
  - {{ n number of dots }}

The thing is i defined `DOTS` as `"."+` so it shouldn't matter the number of dots between the `+`. Can someone explain me if this is a bug? Also it doesn't alternate forever, between `n=5` and `n=7` it doesn't alternate.

**Comment by MegaIng** [comment]
The problem is that they both are valid options to select, so you have an ambiguity. lark with `parser='earley'` will (essentially) choose randomly. Look at https://github.com/lark-parser/lark/blob/master/examples/calc.py for how to design a grammar without this problem.

For this small example

```
?start: term

?term: DOTS (SUM term)?

DOTS: "."+
SUM: "+"
```

would work.

**Comment by scratchmex** [comment]
Thank you
