### ISSUE TITLE
Using regex VERBOSE flag in Lark rules raises LexError

### ISSUE THREAD

**Issue by knutze** [lark-parser/lark#855]
This is my rule.

```lark
HERE_DOCUMENT: /
    <<<(?P<QT>["'])?(?P<ID>\w+)(?(QT)(?P=QT)|)
    .*?
    (?P=ID)(?=;?(?:\r?\n|$))
    /xs
```

I got LexError.

```console
lark.exceptions.LexError: Cannot compile token HERE_DOCUMENT: '(?s:(?x:\n    <<<(?P<QT>["\'])?(?P<ID>\\w+)(?(QT)(?P=QT)|)\n    .*?\n    (?P=ID)(?=;?(?:\r?\n|$))\n    ))'
```

If I write it in one line without the verbose flag, there is no problem.

I am using lark-parser 0.11.2.

**Comment by MegaIng** [comment]
If you scroll futher up, you see the regex exception that is actually thrown. It complains about `nothing to repeat` at position 84. This is the questionmark here: `\r?\n` The problem here is that expansion of  these sequences happens before the regex parser sees them. So they get replaced with the actuall newline symbol, and  then get ignored. Therefor the last symbol the `?` sees is the `(?:` which it ofcourse can't repeat. To fix, just double up the `\`: `(?:\\r?\\n|$)`

**Comment by knutze** [comment]
I am very grateful for the accurate response.
If I write a multi-line regular expression in a lark rule, does that mean that escape sequences are enabled in it?

**Comment by MegaIng** [comment]
@knutze Yes. Everything between `//` is treat as if it were inside a `"""` string literal (no raw, and ofcourse `"""` are escaped before hand properly.)

**Comment by knutze** [comment]
Thanks, I completely understand.

**Comment by knutze** [comment]
I later thought that if it doesn't result in a regular expression compile error, it could be a problem that is hard to figure out the cause. It might be better to have a little explanation in the documentation.
