### ISSUE TITLE
Switch to type-hints using comments

### ISSUE THREAD

**Issue by erezsh** [lark-parser/lark#873]
**Suggestion**

Currently, we are maintaining a separate .pyi file for each .py file, which is slightly cumbersome, and can easily get out of sync.

However, there is another way to do it, while still supporting Python 2: https://mypy.readthedocs.io/en/latest/python2.html

See also this blog post: https://unterwaditzer.net/2019/mypy-and-python2.html

This is just a suggestion for now. I'd like to hear your thoughts.

**Comment by MegaIng** [comment]
My solution to this is to discontinue supporting python2 and python versions <3.6 and switch to inline type hints.

**Comment by erezsh** [comment]
Python2 is still widely used. We would be essentially dropping 25% of our users.

See here: https://www.jetbrains.com/research/python-developers-survey-2017/#python-3-adoption

Maybe in a couple of years it would be a viable choice.

**Comment by MegaIng** [comment]
If you look at the most recent result, it is only 6%: https://www.jetbrains.com/lp/python-developers-survey-2020/

**Comment by erezsh** [comment]
Yeah my bad, just noticed it. It's worth thinking about!

**Comment by MegaIng** [comment]
If you look at the downloads for `lark-parser` it is like 3%: https://pypistats.org/packages/lark-parser But `null` isn't a clear answer so it might be higher.

**Comment by erezsh** [comment]
Also, even without null, some days it gets up to 15% of downloads.

Maybe we can start with a deprecation warning, and see if anyone comes out of the woodwork.

**Comment by MegaIng** [comment]
I think it is fine to discontinue support in new versions. It is not like we are removing the old versions, so we wont break anything. And if I am honest, it is quite a pain to develop: In every PR I have some problem related to python2. Just in the most recent ones:

- `builtins.open` doesn't accept `encoding` as a parameter
- `(*tuple, value)` is not supported
- default encoding was changed
- In general `bytes` vs `str` vs `unicode` is just confusing
- `abc.ABC` does not exist
- All classes need to manually inherit from `object`, otherwise a lot of stuff breaks in subtle ways (e.g. `copy`)

**Comment by j6k4m8** [comment]
I'd very gently also agree that dropping Py2 support is probably okay, with the expectation that existing versions will work in perpetuity for the lingering py2 use-cases. (I say this as someone who has a few py2 lark projects!)

**Comment by JeppeKlitgaard** [comment]
Given that Py2 reached end-of-life more than a year ago and given how much effort I am sure it takes to keep up compatibility, I think bumping the version of Lark and adding a section of the README saying something along the lines of:

> Python 2 support was dropped with version 0.12.x.
> Please use Lark version 0.11.x if you need Python 2 support.

Similarly I think most other projects have dropped/are about to drop Python 2.7 support, so any projects stuck on 2.7 using Lark will probably want to switch to Python 3 eventually due to other libraries dropping support for dead snakes.

A reasonable approach could be to say that Lark drops support in tandem with the official Python Security Support schedule. See: https://endoflife.date/python

This would mean Lark would support 3.6+, which would allow for inline type hinting.

**Comment by erezsh** [comment]
Lark now support 3.6+ only. I think it's safe to close this.
