### ISSUE TITLE
More complete support of regex package

### ISSUE THREAD

**Issue by marsanos** [lark-parser/lark#875]
At present, the features of the `regex` package for extended regexes is not supported. For example, for conditional expressions. This example
```
import lark
g = lark.Lark(
    r"""?start: NAME
        NAME: /(?(?=\d)\d+|\w+)/""", regex=True)
g.parse('123aaa')
```
results in `Bad regexp in token NAME`.

**Comment by MegaIng** [comment]
@erezsh This is because we in `lark.utils.get_regexp_width` use `sre_parse` to disect the regex. This does not have support for the new features in `regex`. We currently provide a hack to support unicode groups, but this of course is not enough. I would suggest on of these options:

- Ditch `get_regexp_width` completely and replace it with `can_match_empty`. This function would just attempt to match the empty string and return a bool.
- New Fallback in `get_regexp_width` that tries to match the empty string and returns something like `(0, MAX_REGEX_WIDTH)` or `(1, MAX_REGEX_WIDTH)`.

Notably is that we only use the max width to sort the patterns in the lexers, so it probably has a most a performance benefit.

**Comment by erezsh** [comment]
@MegaIng I don't want to get rid of `get_regex_width`, because I believe it helps provide the best default priorities. But even if that wasn't the case, it's a breaking change that should wait for v1.0.

The fallback you suggest would work, but might lead to subtle differences in parsing behaviors that would be very hard to debug.

So ideally we should give it a bit more thought before making a final decision either way.

Having said that, this specific error happens in the `EarleyRegexpMatcher` class, which only care about if the regex is 0-length or not. So in that particular case, we can call `can_match_empty` instead, and worry about other configuration paths later.

**Comment by MegaIng** [comment]
> The fallback you suggest would work, but might lead to subtle differences in parsing behaviors that would be very hard to debug.

The fallback would only activate if `sre_parse` fails, which currently leads to a full error, so it wouldn't actually change anything.

**Comment by erezsh** [comment]
A full error is sometimes better than a small unexpected change in behavior..

**Comment by MegaIng** [comment]
Currently, there is no behavior. It isn't a change in behavior, it is addition of new behavior.
