### ISSUE TITLE
Parsing List of Tuples, custom Lexer ... grammar syntax ?

### ISSUE THREAD

**Issue by vsraptor** [lark-parser/lark#948]
I want to parse List-of-Tuples and transform to LoT, like this : 

> word1 word2 ... ==process==> [(word1,tag1), (word2, tag5), (w3,t3) ...] ==parser==> [ predicate1(word2,word5), p2(w2,w1), ...]

example : 

         You will have to join us before the match starts.

         [('You', 'PRON', 'nsubj'), ('will', 'VERB', 'aux'), ('have', 'AUX', 'ROOT'), ('to', 'PART', 'aux'), ('join', 'VERB', 'xcomp'), ('us', 'PRON', 'dobj'), ('before', 'ADP', 'mark'), ('the', 'DET', 'det'), ('match', 'NOUN', 'nsubj'), ('starts', 'VERB', 'advcl'), ('.', 'PUNCT', 'punct')]

https://lark-parser.readthedocs.io/en/latest/examples/advanced/custom_lexer.html#

I can see you can create custom Lexer, but I'm unsure if I create a token f.e. : 

         tok =   { data[0]:1, data[1]: 1, data[2]: 1 }
         yield Token('WORD', tok)

how do I check WORD:

          SVO : WORD.nsubj   WORD*?   WORD.root   WORD*?   WORD.dobj    ???   ## { res += (root, nsubj, pobj ) }

         (have, you, us)

**Comment by erezsh** [comment]
Your question is a little cryptic.

The parser doesn't care about the value of the tokens, only the type, which has to match the name of the terminal in the grammar.

Find the right specifier (either `pobj`, if nsubj <= pobj, or `{nsubj}_{pobj}` otherwise), and use it as the token-type/terminal-name. (note, terminal names must be all uppercase)

**Comment by vsraptor** [comment]
i see .. it seems the TYPE can be used as a MATCH but Attributes are not accessible.
