### ISSUE TITLE
Matched token missing one character and a few other questions

### ISSUE THREAD

**Issue by jjaakko** [lark-parser/lark#983]
I am using Lark 0.11.3 and Python 3.9.6.

1) When running the script below, the value of the FORMULA token will be `\(formula\` while the regular expression for the token is intended to capture a sequence surrounded with backslash and parenthesis such as `\(formula\)` so the captured value is missing the right parenthesis `)`. Why is this? Have I misunderstood something how regexes work with Lark? I tested the regex with https://regex101.com/ and it worked there.

```
from lark import Lark

my_grammar = """
start: thing+

thing: text_or_formula+
text_or_formula: formula|text
formula: FORMULA
text: TEXT_LINE
TEXT_LINE: /((?!\\\()).)+/
FORMULA: /\\\(.+\\\)/

%import common.NEWLINE
"""

text = "text text text \(formula\) text"


def main():
    parser = Lark(
        my_grammar, ambiguity="resolve", parser="earley"
    )
    parse_tree = parser.parse(text)
    print(parse_tree.pretty())
    
    print(parse_tree)


if __name__ == "__main__":
    main()

```
2) If I try to use priorities for rules to simplify the syntax and change the grammar part of the code to the following, everything gets to be picked up as TEXT_LINE although I am trying to specify that when ever the parser could interpret something as FORMULA it should do that. Why the priorities are not working as I expect?

```
my_grammar = """
start: thing+

thing: text_or_formula+
text_or_formula: formula|text
formula.100: FORMULA
text: TEXT_LINE
TEXT_LINE: /.+/
FORMULA: /\\\(.+\\\)/

%import common.NEWLINE
"""
```

3) Any principles, best practices or tips how to maybe make the grammar better? This is the first time I am trying to use Lark.

**Comment by erezsh** [comment]
Regarding (1), it might be due to the need for double-escaping (once for lark, once for the regex)

Try this instead: `FORMULA: "(" /.+/ ")"`

Generally your grammar looks fine. Maybe the rule `text_or_formula` is a bit unnecessary.

I'll try to take a look at (2) tomorrow you don't figure it out by then.

**Comment by jjaakko** [comment]
Thanks for the quick reply! Regarding (1) I tried with your suggestion. It works and makes the syntax more readable! However, I  think the fact that `FORMULA: /\\\(.+\\\)/` does not work _might_ indicate a bug.

I also tested `FORMULA: /\\\(.+\\\)\)/` and it seems to work as well. But to me this is strange (I don't understand **why** having `\)\)` would be needed on the right side of the formula while we only need ` \(` on the left side of the formula). Nevertheless I haven't created a bug issue because maybe I don't understand Lark well enough yet. Curious to hear your thoughts on this.

Is there a documentation on the double-escaping you mentioned? If not, I could try to help in documenting that, provided that I gain sufficient understanding how the double-escaping works. Currently, I am a bit puzzled how double escaping would explain a) why `/\\\(.+\\\)/` seems to not work  and b) why `FORMULA: /\\\(.+\\\)\)/` works.

**Comment by erezsh** [comment]
So, your grammar string should be prefixed with `r`, for a raw string. Otherwise, Python will be doing its own escaping as well, before Lark even gets it.

And then this code works for me: 

```python
>>> Lark(r'start: /\(\w+\)/').parse('(abc)')
Tree('start', [Token('__ANON_0', '(abc)')])
```

So if you think there is a bug, you'll have to show it, ideally in a short and simple example.

I'm guessing (2) is happening because of (1). So let's do them in order.

**Comment by MegaIng** [comment]
Note that there is actually triple (half-) escaping going on:

Your string literal is not marked as raw, so python already does a layer of escaping. This however is only half a step: It turns `\\\(` into `\\(` (Since `\(` is not a correct escape sequence).

Lark does another half escaping step, which turns `\\(` into `\\(`, i.e. it doesn't change anything (Not sure why right now).

The regex engine does one final step and uses that result: It sees a literal `\\` and an opening bracket `(` and starts a group. Based on that, the result you see makes sense. Your major problem is actually inside `TEXT_LINE`, which has the sequence `\\\()` inside which matches just backslash, which is not what you want.

This grammar works for me:

```
my_grammar = r"""
start: thing+

thing: text_or_formula+
text_or_formula: formula|text
formula: FORMULA
text: TEXT_LINE
TEXT_LINE: /((?!\().)+/
FORMULA: /\(.+\)/

%import common.NEWLINE
"""
```

**Comment by jjaakko** [comment]
Thanks! Building on your answers I was able to make it work with this one (as I want capture the `\` before the parenthesis as well):

```
my_grammar = r"""
start: thing+

thing: text_or_formula+
text_or_formula: formula|text
formula: FORMULA
text: TEXT_LINE
TEXT_LINE: /((?!\\\().)+/
FORMULA: /\\\(.+\\\)/

%import common.NEWLINE
"""
```
So definitely no bug related to (1). Do you think that more documentation could be useful regarding this?

Regarding (2). I am using the following, trying to pick up formula but everything gets picked up as text. Probably something that I have not understood correctly regarding priorities.

```
my_grammar = r"""
start: thing+

thing: text_or_formula+
text_or_formula: formula|text
formula.100: FORMULA
text.-100: TEXT_LINE
TEXT_LINE: /.+/
FORMULA: /\\\(.+\\\)/

%import common.NEWLINE
"""
```

**Comment by erezsh** [comment]
I'm open to additional documentation, if you can think of anything that will help.

Re (2), Can you also provide an example input?

**Comment by jjaakko** [comment]
Sure, the full example is below. So input is actually the same: `text text text \(formula\) text`

```
my_grammar = r"""
start: thing+

thing: text_or_formula+
text_or_formula: formula|text
formula.100: FORMULA
text.-100: TEXT_LINE
TEXT_LINE: /.+/
FORMULA: /\\\(.+\\\)/
"""

text = "text text text \(formula\) text"


def main():
    parser = Lark(
        my_grammar, ambiguity="resolve", parser="earley"
    )
    parse_tree = parser.parse(text)
    print(parse_tree.pretty())
    print(parse_tree)


if __name__ == "__main__":
    main()
```

**Comment by erezsh** [comment]
Right, so it's pretty simple.

At position 0, the lexer can't match FORMULA, so it matches TEXT_LINE. And because TEXT_LINE can match the entire line, that's what it does.

The easiest solution is to tell the lexer to stop matching TEXT_LINE when it's time:

```lark
TEXT_LINE: /((?!\\\().)+/
```

**Comment by jjaakko** [comment]
Ok, now it makes perfect sense, thanks so much!

**Comment by erezsh** [comment]
Happy to help!

Feel free to open a PR if you have ideas to improve the docs.
